### ISSUE TITLE
Feature Request: UnicornDash

### ISSUE THREAD

**Issue by kennyparsons** [UnicornTranscoder/UnicornTranscoder#107]
I'd love to see a Dashboard showing a high level view of the transcoders. Call it UnicornDash. 

Currently, I have to navigate to all instances of the transcoders to see which ones are in use. Further, I cannot tell which stream is tied to which transcoder. Another item I'd like to see is the performance of the each node running the transcoder, like cpu/memory/etc.

**Comment by kennyparsons** [comment]
UnicornDash could be installable on any machine, as long as it can access the LoadBalancer and Transcoder (via https).

**Comment by Maxou44** [comment]
I would love to patch plex routes on-the-fly and add informations in Plex dashboard

**Comment by zapoklu** [comment]
As a short term solution, i'm using the loadbalancer to check which servers are in use

wget http://loadbalancer.domain.com:3001/api/stats

the sessions are returned in json format which should be pretty easy to parse. i then use that to determine if i need to scale up or down my transcoder nodes :)
