### ISSUE TITLE
Updates and Version Matching

### ISSUE THREAD

**Issue by kennyparsons** [UnicornTranscoder/UnicornTranscoder#108]
I don't see much in the way of updating and version matching.

1. Updating: Can I assume that updating can be done by pulling from github and re-building? 

2. Version Matching: For UnicornTranscoder, I see three variables that can change at any time: 

- Plex build 
- Codecs build
- Easy Audio Encoder version

Do these versions need to match the plex server version exactly to work? For example, if my plex container updates overnight, will the UnicornTranscoder stop working if it's using a different build/codec/EAE?

**Comment by Maxou44** [comment]
We try to update Unicorn Project as soon as possible when Plex update it. We recommend to disable automatic plex updates, some updates can break stuff in transcoder and need to be fixed. We publish a release each time we have a stable version.

If you want to update to unsupported build, you have to edit the 3 variables in your UnicornTranscoder with your plex version and rerun the install. You can find information how to get these values from "Plex Media Server" binary in the README

**Comment by kennyparsons** [comment]
Sounds good.
