### ISSUE TITLE
New updatable version

### ISSUE THREAD

**Issue by davidjameshowell** [UnicornTranscoder/UnicornTranscoder#112]
Not an issue!

I don't have a PR ready for this, but for what it is worth, these versions are still valid and compatible with UnicornTranscoder:

```
plex_build: 1.20.4.3517-ab5e1197c
codecs_build: 02cff92-3522
eae_version: eae-69c1de6-42
```

These are current and update to date. I tested these against Android App, Chromecast, and Web Player and all were successful in starting, playing, serving direct play and transcoding. Cannot comment on other paths, but it's looking like a solid upgrade.

**Comment by Maxou44** [comment]
Thanks for the feedback 😉
I will release it soon 😉

**Comment by davidjameshowell** [comment]
For future references - what type of regression testing should be done to validate a new Plex version? Is there a release criteria for new versions?

**Comment by Maxou44** [comment]
Updated!
By experience, if Plex team don't talk about the "transcoder" part in the changelog, there is no risk to update directly. 
For advanced testing, we check from Plex Web (to test DASH stream), Plex for Windows/Mac (to test long polling stream) and Android or iOS (to test HLS stream). All these tests are realized using the transcode feature, there is no issue with direct play, it's a download link.
We also try with the following subtitles formats : SRT, external SRT, PGS and ASS.
And if everything is good we can update 😉
