### ISSUE TITLE
skip intro detection

### ISSUE THREAD

**Issue by thecoolreaver** [UnicornTranscoder/UnicornTranscoder#114]
I am noticing that the process running that handles scanning for intros for TV content is stuck and running. From what I can see its trying to run the Plex Transcoder which is the fake one from the FFMPEG repo but it uses a different path. I am not sure what information or logs you would like me to provide to help make getting this working.

https://support.plex.tv/articles/skip-content/

Edit: tried with both master and alpha branches

**Comment by Maxou44** [comment]
Normaly, when the transcoder is correctly set up, you can stream content and there is no issue with the "skip intro" feature.
Can you share us your load balancer and transcoder configurations ? Can you provide us logs when you try to start a movie ?

**Comment by thecoolreaver** [comment]
I found the issue from a error I was seeing (I do not have the logs anymore) but it was trying to write/read from a config folder that was not available (running plex in docker). In the host, I made a symbolic link to the config folder (ln -s /opt/plex/config /config) and that seems to have fixed the issue.

**Comment by Maxou44** [comment]
Thanks for the update, I will close the issue 😉
