### ISSUE TITLE
routing overriding maxtranscodes

### ISSUE THREAD

**Issue by thecoolreaver** [UnicornTranscoder/UnicornTranscoder#118]
I made a small modification to routing to be instead of country to be states (almost everyone is in the states for me and ISP backbone routing sucks) and placed servers closer to the major of my users. The issue I am having is these servers are not powerful for transcoding so I set the "maxTranscodes" to be "-1" but the routing option seems to override that. Based on the code here ( https://github.com/UnicornTranscoder/UnicornLoadBalancer/blob/a2713845431002379a2c7279e276bb02622bf171/src/core/servers.js#L70 ) setting it to "-1" sets the load to +5.

I do notice that under the performance section ( https://github.com/UnicornTranscoder/UnicornTranscoder#performance-configuration ) that it states its not a hard limit but is there a way to have it doing the routing after..

Based on the code, I am thinking a routing on the loadbalancer instead of the transcoder would work better with how the load is calculated on there but I am not exactly sure how to code that.

Edit:

Also changing it the routing places on on central loadbalancer location instead of having to update many transcoder satellites would be nice

**Comment by Maxou44** [comment]
Sorry for the delay I didn't see your issue earlier.

What is your excepted behavior, you want to redirect all the download/direct play on cheap servers and transcode on powerful servers?

We talked about a "transcoder capabilities" feature in the past, maybe it could solve your issue if we support it? 
https://github.com/UnicornTranscoder/UnicornTranscoder/issues/57
