### ISSUE TITLE
codecs_build regex no longer working

### ISSUE THREAD

**Issue by BuffaloBun** [UnicornTranscoder/UnicornTranscoder#133]
[codecs_build regex](https://github.com/UnicornTranscoder/UnicornTranscoder/blame/master/README.md#L83) is not working for Plex Media Server `1.23.1.4528-c0513eb4c`, the regex should find `fa235d6-3858` but it returns nothing.
This also breaks the [unofficial docker](https://github.com/magn2o/unicorn-docker/blob/master/unicorn-transcoder/rootfs/etc/cont-init.d/00-setenv#L22).

Temporary workaround is to manually look in `.../Library/Application Support/Plex Media Server/Codecs` on your Plex server and manually set the codec value in your Transcoder [config.js](https://github.com/UnicornTranscoder/UnicornTranscoder/blob/master/config.js#L20), if the docker image is used.

**Comment by Maxou44** [comment]
Can you have a look @drouarb

**Comment by Maxou44** [comment]
You can use ```strings "Plex Transcoder" | grep -Po '[0-9a-f]{7}-[0-9]{4}$'```, I will update the README 😎

**Comment by Maxou44** [comment]
Can you confirm it works without issue on :

plex_build: 1.23.2.4600-f06057b33
codecs_build: fa235d6-3858
eae_version: eae-69c1de6-42

Have a great day,
Maxime
