### ISSUE TITLE
Plex 1.23 - Transcoder gives 404 on /video(/:/transcode)

### ISSUE THREAD

**Issue by GRX** [UnicornTranscoder/UnicornTranscoder#136]
I've installed the transcoder, and I can see the status page on `transcoder.domain.com` where it says "Congrats! The UnicornTranscoder is correctly launched!"

But when I start a video in Plex, the console fills with errors.
`Failed to load resource: the server responded with a status of 404 () - https://transcode.domain.com/video/:/transcode/universal/session/nkg1u8ouipdt0491lfqqc8hh/0/39.m4s` 

The server log is getting flooded with: 
```
[Transcode] Transcoder segment range: 0 - 1 (1)
[Transcode] Transcoder segment range: 0 - 2(2)
[Transcode] Transcoder segment range: 0 - 3 (3)
[Transcode] Transcoder segment range: 0 - 4 (4)
[Transcode] Transcoder segment range: 0 - 5 (5)
etc...
```

The transcoder is also registered at plex.domain.com/api/stats, which give the following:
```
{
    "https://transcoder.domain.com": {
        "name": "https:///transcoder.domain.com",
        "sessions": [],
        "settings": {
            "maxSessions": 10,
            "maxDownloads": 10,
            "maxTranscodes": 10
        },
    "url": "https://loadbalancer.domain.com",
    "time": 1623703360,
    "score": 0
    }
}
```

Logging the transcoder container shows nothing other than the startup information:
```
[cont-init.d] 01-install-transcoder: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

> UnicornTranscoder@2.5.1 start /opt/UnicornTranscoder
> node ./bin/www
```

Did I miss something in my setup here?

Thank you in advance!

**Comment by GRX** [comment]
In addition:
`start.mpd?` on the loadbalancer redirects with a 307(?) to the transcoder.
Then after a second or then I get `trascoder.domain.com /video/:/transcode/universal/start.mpd? - 200 OK` back from the transcoder and all requests like `https://transcoder.domain.com/video/:/transcode/universal/session/tufjpsrho53lc8fts4bodsuo/0/0.m4s` start to fail.

**Comment by Maxou44** [comment]
In the network target of your browser can you get the link of the 404 request and open it in a new target, it will display somenthing "callback xxx", il will help us to debug. In general it's a misconfiguration and the transcoder can't start or it don't have access to files. Did you ran a "npm run install" in the transcoder folder ?

**Comment by GRX** [comment]
> In the network target of your browser can you get the link of the 404 request and open it in a new target, it will display somenthing "callback xxx", il will help us to debug. 

When I open any of the failed requests, it just gives me `Cannot GET /video/:/transcode/universal/session/aqmryo9vpxryzjsv0fx4dke2/1/0.m4s`.


> In general it's a misconfiguration and the transcoder can't start or it don't have access to files. 

Which files should these be? I mounted the media folder at the same path that Plex has it's media mounted. So within the containers they both access files via `/media(/movies-/shows)`.


> Did you ran a "npm run install" in the transcoder folder ?

I'm using the `magn2o/unicorn-transcoder` image, since everything is starting and codecs are also being installed at launch, I assume everything is working correctly? I have it started with the debug option, but after starting no debug information is showing.

Env;
- PLEX_BUILD="1.23.2.4656-85f0adf5b"
- SERVER_PORT="3000" _(the instance address reverse proxies to this port)_
- LOADBALANCER_ADDRESS="https://loadbalancer.domain.com"
- INSTANCE_ADDRESS="https://transcoder.domain.com:443"
- PLEX_TOKEN="${PLEX_TOKEN}"

When I start playing something in Plex, it loads forever and I can see in `/api/stats` that a session has started on the transcoder with the status `DONE` immediately, even though the player is still trying to connect.

When I check the transcoder, I see;
```
Current transcodes     | 0
Current sessions       | 1
Current downloads      | 0
```

So the session reaches the transcoder? But it simply isn't starting.

**Comment by GRX** [comment]
So 1 step further, I've been changing the URLs in `routes.js` to accomodate the incoming requests and now I get either;
```
Callback -1
``` 
**or**
``` 
Error: ENOENT: no such file or directory, stat '/opt/UnicornTranscoder/cache/{removed_session_id}/chunk-stream1-00001.m4s'
```

When doing a request. So I indeed believe that it can't reach the files, I can see in the `cache` directory that the session folder is being created. How can I check where the Transcoder is looking for the video files?

**Comment by Maxou44** [comment]
Fixed :)
