### ISSUE TITLE
Support Infuse (3rd party app)

### ISSUE THREAD

**Issue by Maxou44** [UnicornTranscoder/UnicornTranscoder#25]
The app Infuse support Plex in its latest version, this app can direct stream a lot of files on Apple TV and iOS, but actually it don't work with the transcoder/load balancer.

https://firecore.com/infuse

**Comment by Cimplex** [comment]
I help Infuse get reverse proxies working for Plex. Do you have any more details on this? I can help initiate a dialog.

**Comment by Cimplex** [comment]
Makes sense, as I believe they weren't looking at the correct connect URLs before the 5.7.4 update which came out at the end of June.

An aside, I just started going through your project to see how I can use it. Looks good!
