### ISSUE TITLE
What is "Plex Library" aka "The path to to your library root"

### ISSUE THREAD

**Issue by r2d2leboss** [UnicornTranscoder/UnicornTranscoder#27]
Hello,

What do you mean by `mount_point` aka "The path to to your library root" ? 

My Plex server have multiple libraries (Movies, TV Shows, ...) . Each library has multiple paths (/movies, /tv-show, /movies-en, ...). So I don't get exactly what's expected. I don't find much on Google about "Plex Library". Is Plex Library the place where files are or an internal lib path of Plex ?

It would also be nice to have an illustration with a global overview of the architecture, what connections between different services / servers, ports, shared files, ...

Thanks

**Comment by Maxou44** [comment]
It's an optionnal feature to mount your data on another drive, for example if all my data are stored `/mnt/plex` I can mount it on another month point on the transcoder like '/mnt/data`. If your data is available in the same mount point on the main server and on transcoders set your mount point to `/`

**Comment by descention** [comment]
What happens if you have multiple mount points? I use `/media/nas` and `/media/ceph`. If I mount the same paths on all transcoders, it should work with the `/`?

**Comment by Maxou44** [comment]
If you have the same mount point use /, it will work 😀
