### ISSUE TITLE
HDR Stream and/or Tonemapping

### ISSUE THREAD

**Issue by camjac251** [UnicornTranscoder/UnicornTranscoder#29]
I haven't had a chance to try this out yet but was wondering if HDR is supported. If screenshots and video previews are created with Unicorn, could it tonemap HDR streams to screenshots. Or if a transcode is happening, could it preserve the BT.2020 color space so it's passed onto the client?

**Comment by Maxou44** [comment]
The UnicornTranscoder executes FFMPEG with the plex parameters, if Plex supports HDR, it will also support it, thumbnails aren(t generated by UnicornTranscoder
