### ISSUE TITLE
 Failed to find session id

### ISSUE THREAD

**Issue by b-rockx** [UnicornTranscoder/UnicornTranscoder#30]
Plex keeps giving me the error ```Failed to find session id``` when starting a video. I see no other errors in the other applications (trancoder, load balancer, FFMPEG).

**Comment by drouarb** [comment]
This error is not a Plex error, it's just Plex displays the output of UnicornFFMPEG in his logs, you should dig on this way

**Comment by b-rockx** [comment]
What logs should I be looking at? I can't seem to find the logs for UnicornFFMPEG.

**Comment by drouarb** [comment]
UnicornFFMPEG is a binary executed by Plex for each stream, the output of UnicornFFMPEG is in the Plex Media Server.log. UnicornFFMPEG uses a regex to parse the sessionid, this regex is based on the progress url used by Plex. This URL is hardcoded, maybe you are not using port 32400 ? You should create an issues on UnicornFFMPEG project.

**Comment by b-rockx** [comment]
I'm using port 32400. I looked at the Plex Media Server.log file and didn't see good info on why it didn't work. it did send a request using 127.0.0.1:32400 but never plays after that.

**Comment by drouarb** [comment]
Just though about something, did you enabled Keyspace Notifications on your Redis server. I forgot to metion it and it is mandatory to make the project works.
