### ISSUE TITLE
Different Database Types

### ISSUE THREAD

**Issue by DrEVILish** [UnicornTranscoder/UnicornTranscoder#36]
Add support for other keyvalue store DBs

Having to install a whole redis server just for UnicornTranscoder is rather heavy when you might already have etcd... etc... already setup and installed.

etcd is designed to be clustered by nature, which eliminates a single point of failure and load balances the requests.

**Comment by drouarb** [comment]
The v2 of the transcoder does not need redis anymore, only the LoadBalancer support redis for storing sessions but it's not mandatory anymore.
