### ISSUE TITLE
iOS App can not connect?

### ISSUE THREAD

**Issue by raphaelfumfahr** [UnicornTranscoder/UnicornTranscoder#39]
Hello, there,

I installed the Transcoder and Loadbalancer, now I wanted to connect to my mobile using the External Server function. Since the 32400 port is disabled for other users. Now I tried to connect to the port of the LoadBalancer (3001) and my IP of the LoadBalancer and got only a 401 error message. Anyone have any idea why? On my Smarttv works fine...

**Comment by drouarb** [comment]
401 is a plex error since the loadbalancer also act as a reverse proxy, you have to setup a custom url to access the server with the port of the loadbalancer, also you should deny all connection on port 32400 to prevent any app to connect directly to plex

**Comment by raphaelfumfahr** [comment]
A URL was set up and redirected to port 3001 with SSL, and port 32400 was also denied via iptables. But the Plex APP required an IP address instead of a URL. If I enter this IP address and port 3001, I get this 401 error.

**Comment by drouarb** [comment]
The unicorn transcoder and loadbalancer does not support SSL, you have to setup a reverse proxy to enable SSL support

**Comment by raphaelfumfahr** [comment]
Yeah the Domain has the SSL, this is not supportet? The domain redirect with a reverse proxy to <IP>:3001, and the same on the Transcoder <IP>:3000.

**Comment by drouarb** [comment]
So if you have a reverse proxy, like nginx, you should setup the SSL there with the SSL certificate. Also, the custom URL should point to the reverse proxy address.

**Comment by raphaelfumfahr** [comment]
I did it.

but that doesn't help with the Plex APP because it only works with IP.

**Comment by drouarb** [comment]
You don't need to put the IP, normally the plex app find your serv based on your account

**Comment by raphaelfumfahr** [comment]
Yeah?

But only with port 32400? But the LoadBalancer runs on 3001? Port 32400 is deactivated from the outside with iptables? im confused...

**Comment by drouarb** [comment]
The way plex work is the following:
PMS register few access URLs on plex.tv:
The custom URL you registered in the preference
An url per network interface
Plex repay url

When you connect, the client will fetch these urls and try to connect to it
The goal is to redirect all connections in the loadbalancer.
So what it should do is nginx->lb->plex, that's why you have to deny 32400 to only allow access through the custom url

**Comment by drouarb** [comment]
If you have a 401 when you connect with a browser on the loadbalancer address, it's normal, it's just plex that deny the connection because you are not authenticated

**Comment by raphaelfumfahr** [comment]
Ah okay, can u check my Nginx config and my iptables?

**Comment by drouarb** [comment]
For me, your config looks fine, do you see your iOS app in the nginx log ?

**Comment by raphaelfumfahr** [comment]
I see no error mhmm...

Is that a good idea with PlexGuide and Docker? or should I install Plex manually?
I also don't know if the IP tables the Docker sets are correct

**Comment by drouarb** [comment]
Do you see the request of your iOS app in your nginx log ? I didn't tried PlexGuide, I run it with a manual Plex installation. Currently UnicornTranscoder is pretty tricky to install, I'm working on an easier version to install

**Comment by raphaelfumfahr** [comment]
Hi,

Now I installed Plex manually, now I get "Plex server is not available" on my smartphone, everything works fine in the browser. With and without Plex Relay it doesn't work.

**Comment by drouarb** [comment]
Did you put the custom url in Plex settings ?

**Comment by raphaelfumfahr** [comment]
Yes with https

an now crash all time the pms server with this error:

Nov 30, 2018 04:18:06.188 [0x7fce113f6700] ERROR - [PlexRelay] connect_to localhost port 32401: failed.
Nov 30, 2018 04:18:06.310 [0x7fce11bf7700] ERROR - [PlexRelay] connect_to localhost port 32401: failed.
Nov 30, 2018 04:18:09.265 [0x7fce123f8700] ERROR - [PlexRelay] connect_to localhost port 32401: failed.
Nov 30, 2018 04:18:09.388 [0x7fce10bf5700] ERROR - [PlexRelay] connect_to localhost port 32401: failed.
Nov 30, 2018 04:18:10.428 [0x7fce113f6700] ERROR - [PlexRelay] connect_to localhost port 32401: failed.
Nov 30, 2018 04:18:10.554 [0x7fce11bf7700] ERROR - [PlexRelay] connect_to localhost port 32401: failed.

**Comment by drouarb** [comment]
Which OS do you use ? Did you restarted PMS ?

**Comment by drouarb** [comment]
So it's a setup problem, do your sessions appear in the redis ?

**Comment by drouarb** [comment]
Also open the chrome dev tools and check the url of start.mpd

**Comment by raphaelfumfahr** [comment]
i find no start.mpd on the console, or quellcode

**Comment by drouarb** [comment]
In the devtools of chrome, in the network tab when you transcode, it should call something like /:/transcode/universal/start.mpd, check if the domain and the port is the one from the loadbalancer

**Comment by raphaelfumfahr** [comment]
i remove this: iptables -A INPUT -p tcp --dport 32400 -i eth0 -j DROP
on the iptables and the indirectly is gone...

with no iptable rules: its my server ip adress and the 32400 Port, with plex.direct url.
with iptables rule and indirectly connect ont the app.plex.tv site: no ip adress from me, and plex.direct:8443 port

**Comment by drouarb** [comment]
This means that the plex custom url is not correctly registered, check the Custom server access URLs https://support.plex.tv/articles/200430283-network/

**Comment by drouarb** [comment]
8443 port is the Plex Relay port, it also bypass the loadbalancer, the traffic isn't going through the loadbalancer

**Comment by raphaelfumfahr** [comment]
I Delete again the Plex Relay and worked .... with the custom URL and plex crash again? after restart workend again, and i play any video crash again

**Comment by raphaelfumfahr** [comment]
i need the Plex Custom URL with port? or no port?

e.g.
https://plex.mycustomdomain.com:3001
or
https://plex.mycustomdomain.com

**Comment by drouarb** [comment]
It should be https://plex.mycustomdomain.com:443 because the HTTPS is on the nginx reverse proxy

**Comment by raphaelfumfahr** [comment]
Is this normal Plex say: Not available outside your network?

now its worked on my smartphone? ähhhhhhh okaaay?

**Comment by drouarb** [comment]
Yes it's normal because PMS ask plex.tv to ping him so plex.tv ping your server on 32400 but you don't want anything go to PMS directly so you deny any communication on 32400.

**Comment by raphaelfumfahr** [comment]
Ah okay :) Delete Plex Relay again now its work i hope... i think this was the error?

**Comment by drouarb** [comment]
Also you can try on chrome, if it works well in the network tab you should see the loadbalancer sending you a 302 on the transcoder

**Comment by raphaelfumfahr** [comment]
Yes, he gives me a 302 redirect to the transcoder :) thanks for your TIME to help me! :)

**Comment by drouarb** [comment]
No problem, I know it's tricky to install, soon there will be the V2 and the Dockers
