### ISSUE TITLE
Try to get version 2 to run

### ISSUE THREAD

**Issue by raphaelfumfahr** [UnicornTranscoder/UnicornTranscoder#44]
I've taken the following steps:

With UnicornFFMPEG I generated the Plex transcoder and swapped it with the original, deleting "Plex Relay" as well. In it I define the UnicornLoadBalancer URL like e.g. https://domain.com/.

Then I install the UnicornLoadBalancer and change the following values in src/config.js:

SERVER_PUBLIC to https://domain.com/
I leave DATABASE_MODE on sqlite.

Then I create iptable entries to block port 32400:

```
sudo iptables -A INPUT -p tcp --dport 32400 -i eth0 -s XX.XX.XX.XX -j ACCEPT
sudo iptables -A INPUT -p tcp --dport 32400 -i eth0 -j DROP
```

And then we come to the UnicornTranscoder, first I install it well-behaved with "npm install", set the LOADBALANCER_ADDRESS to "https://domain.com" and the INSTANCE_ADDRESS to "https://transcoder.domain.com" everything else I leave on default.

The UnicornLoadBalancer domain was still stored at Plex in the network tab with "https://domain.com".

Now I am not redirected to the transcoder via 302, port 32400 is somehow not blocked, and I get the following in the log of the UnicornLoadBalancer:

```
npm start

> unicorn-load-balancer@2.0.0 start /home/plex/LoadBalancer
> node index.js

FFMPEG CALLED 1
FFMPEG CALLED 2
FFMPEG ade7bblx2v4zv05hi1vz4lk9 { args:
   [ '-codec:0',
     'h264',
     '-codec:1',
     'dca',
     '-ss',
     '0',
     '-noaccurate_seek',
     '-probesize',
     '10000000',
     '-i',
     'https://domain.com/library/parts/3/0/file.stream?download=1',
     '-filter_complex',
     '[0:1] aresample=async=1:ocl=\'stereo\':osr=48000[0]',
     '-map',
     '0:0',
     '-metadata:s:0',
     'language=eng',
     '-codec:0',
     'copy',
     '-map',
     '[0]',
     '-metadata:s:1',
     'language=ger',
     '-codec:1',
     'aac',
     '-b:1',
     '256k',
     '-f',
     'dash',
     '-min_seg_duration',
     '5000000',
     '-skip_to_segment',
     '1',
     '-time_delta',
     '0.0625',
     '-manifest_name',
     '{INTERNAL_TRANSCODER}video/:/transcode/session/ade7bblx2v4zv05hi1vz4lk9/79082013-1fb8-463c-943a-aa48e4054e06/manifest',
     '-avoid_negative_ts',
     'disabled',
     '-map_metadata',
     '-1',
     '-map_chapters',
     '-1',
     'dash',
     '-start_at_zero',
     '-copyts',
     '-vsync',
     'cfr',
     '-y',
     '-nostats',
     '-loglevel',
     'quiet',
     '-loglevel_plex',
     'error',
     '-progressurl',
     '{INTERNAL_TRANSCODER}video/:/transcode/session/ade7bblx2v4zv05hi1vz4lk9/79082013-1fb8-463c-943a-aa48e4054e06/progress' ],
  env:
   { EAE_ROOT: '/tmp/pms-54915d4a-3244-4cfd-bd35-cdd4b37c4168/EasyAudioEncoder',
     FFMPEG_EXTERNAL_LIBS: '/var/lib/plexmediaserver/Library/Application\\ Support/Plex\\ Media\\ Server/Codecs/531e313-1328-linux-ubuntu-x86_64/',
     HOME: '/home/plex',
     INVOCATION_ID: '0ebca021523440f18137a12804d1f9d0',
     JOURNAL_STREAM: '9:49159',
     LANG: 'en_US.UTF-8',
     LD_LIBRARY_PATH: '/usr/lib/plexmediaserver',
     LIBVA_DRIVERS_PATH: '/usr/lib/plexmediaserver/dri',
     LOGNAME: 'plex',
     PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
     PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR: '/var/lib/plexmediaserver/Library/Application Support',
     PLEX_MEDIA_SERVER_HOME: '/usr/lib/plexmediaserver',
     PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS: '6',
     PLEX_MEDIA_SERVER_TMPDIR: '/tmp',
     PWD: '/',
     SHELL: '/bin/bash',
     USER: 'plex',
     XDG_CACHE_HOME: '/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Cache',
     XDG_DATA_HOME: '/usr/lib/plexmediaserver/Resources',
     X_PLEX_TOKEN: 'XXXXXXXXXXXXXXXX' },
  session: 'ade7bblx2v4zv05hi1vz4lk9',
  sessionFull: 'ade7bblx2v4zv05hi1vz4lk9/79082013-1fb8-463c-943a-aa48e4054e06' }
```

Now the question is, what did I do wrong? Unfortunately I can't get any further.

**Comment by Maxou44** [comment]
Thanks for logs, the FFMPEG is well installed, and the load balancer setup looks great too.
In the network settings of your browser, can you check the link of the start request?
I think plex uses its own DNS to call your server (on 32400 port which is apparently not correctly blocked)
What happen if you typein a browser: http://<your-ip>:32400/  ?
Do you use a reverse proxy like Nginx to bind the server name and the load balancer port ?

**Comment by raphaelfumfahr** [comment]
Hey,

When I search for XHR in Network using DevTools, Plex forwards the request to my Plex Server IP with plex.direct and not to the transcoder so the start.mpd file.

Yes, I use Nginx proxy to connect the LoadBalancer URL and the Transcoder URL, so that the whole thing also runs via SSL, everything is routed via reverse proxy to the ports.

When I connect via https://domain.com:32400 he directs me to the https://domain.com:32400/web/index.html directory of Plex, and shows me Plex.

**Comment by Maxou44** [comment]
Okay, the problem is the 32400 port, can you try to clean your iptables and use this rule:
`iptables -A INPUT -p tcp --dport 32400 -i eth0 -j DROP`

**Comment by raphaelfumfahr** [comment]
I've been betting the same value since the beginning. See picture.
![iptable](https://user-images.githubusercontent.com/6332358/53443053-10a7e280-3a0b-11e9-85a4-868746aaf14a.png)

Something wrong?

**Comment by Maxou44** [comment]
I see 3 rules on your screenshot, can you remove rules 1 and 2?

**Comment by raphaelfumfahr** [comment]
Yes I can, I took this as a reference and the two entries are my transcoders.

Example iptable
#Allow transcoders to reach the Plex Media Server
iptables -A INPUT -p tcp --dport 32400 -i eth0 -s <transcoderIP> -j ACCEPT
#Deny all other incoming connections
iptables -A INPUT -p tcp --dport 32400 -i eth0 -j DROP

**Comment by Maxou44** [comment]
It was a mistake from our side, since the 2.0, it's not require to allow transcoders ip, you can drop everything, can you try?

**Comment by raphaelfumfahr** [comment]
I deleted the entries, unfortunately no changes. http://IP:32400 is still open, just like 3001 forwarded me to Plex.

**Comment by Maxou44** [comment]
Can you try that:
`iptables -A INPUT -i [network-interface] -p tcp -m tcp --dport 32400 -j DROP`

**Comment by raphaelfumfahr** [comment]
> Can you try that:
> `iptables -A INPUT -i [network-interface] -p tcp -m tcp --dport 32400 -j DROP`

I just changed from eth0 to enp0s31f6, now 32400 is blocked, but now I can't get a connection via https://app.plex.tv anymore.

**Comment by Maxou44** [comment]
Nice! So now, you need to change some stuff in Plex parameters ✌

In advanced mode, go to "Network" and set "Custom server access URLs" to "https://my-server" and click on "Save", now go in "Remote acess" and set the port to "443".

Then it should work (I hope)

**Comment by raphaelfumfahr** [comment]
I think its worked! 🎉🍻

**Comment by Maxou44** [comment]
Awesome! 🥳

Pro-tip: If your media files are also available on your transcoders set `CUSTOM_DOWNLOAD_FORWARD` to `true`, you will have a performance improvement ✌

If it's possible can you give us a feedback about our documentation and your setup? Was it simple? Complicated? What did you struggle with?

**Comment by raphaelfumfahr** [comment]
Hey. Hey. Hey,

With rclone I have integrated a Team Drive from Google, on every transcoder, does this work with "CUSTOM_DOWNLOAD_FORWARD=true" also there? Or do they have to be local?

Actually it was quite simple, but I would add an Example Nginx Config to the documentation to have the optimal proxy settings. Furthermore I don't like the getenv very much, I usually work with a .env file, which is simpler in my opinion. But in itself really well done! :)

I use as Plex server:
i7-6700 Quad-Core
64 GB DDR4 RAM
2x 512 GB NVMe SSD as raid
1GB bandwidth 

Transcoders:
AMD Ryzen 7 1700X Octa-Core
64 GB DDR4 RAM
2x 500 GB SATA SSD in software Raid 0
1GB bandwidth

**Comment by Maxou44** [comment]
If rclone is mount on the same path it will works 😉

By default (false value) the transcoder will fetch the file from the load balancer (it's not optimal but easier to setup in a lot of case), if it's set to true, the transcoder will serve the file itself from his filesystem.

I fixed some details in the LoadBalancer documentation (iptables and Plex settings after the port drop)

We use a tricky nginx configuration on our side, if you can share yours it could be nice 😁

**Comment by raphaelfumfahr** [comment]
Okay, I'm testing this whole thing. :)

Does the synchronization work in the apps? With the transcoder?

I can post it, but it's also not the yellow one from the egg. 🤣🤣

LoadBalancer:
```
# Virtual Host configuration for domain.com
#
# You can move that to a different file under sites-available/ and symlink that to sites-enabled/ to enable it.
server {
	listen [::]:443 ssl ipv6only=on; # managed by Certbot
	listen 443 ssl; # managed by Certbot
	server_name domain.com;
	
	ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem; # managed by Certbot
	ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem; # managed by Certbot
	include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
	ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
	
	client_body_timeout 240m;
	
	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;
	
	location /.well-known/acme-challenge {
		auth_basic off;
		allow all;
		alias /var/www/.letsencrypt;
	}
	
	location / {
	
		# Specific rule for /
		if ($http_x_plex_device_name = '') {
			set $test A;
		}
		if ($arg_X-Plex-Device-Name = '') {
			set $test "${test}B";
		}
		if ($test = AB) {
			rewrite ^/$ http://$http_host/web/index.html;
		}

		# Proxy configuration
		proxy_pass http://127.0.0.1:3001;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		
		# Plex proxy settings.
		proxy_redirect      off;
		proxy_buffering     off;
		
		# Required for Websockets
		proxy_http_version      1.1;
		proxy_set_header        Upgrade         $http_upgrade;
		proxy_set_header        Connection      "upgrade";
		proxy_read_timeout      36000s;         ## Timeout after 10 hours
		proxy_send_timeout     36000s;
		proxy_connect_timeout  36000s;
	}
}
server {
	if ($host = domain.com) {
		return 301 https://$host$request_uri;
	} # managed by Certbot
	
	listen 80;
	listen [::]:80;
	
	server_name domain.com;
	return 404; # managed by Certbot
}
```

Transcoder:
```
# Virtual Host configuration for transcoder.domain.com
#
# You can move that to a different file under sites-available/ and symlink that to sites-enabled/ to enable it.
server {
	listen [::]:443 ssl ipv6only=on; # managed by Certbot
	listen 443 ssl; # managed by Certbot
	server_name transcoder.domain.com;
	
	ssl_certificate /etc/letsencrypt/live/transcoder.domain.com/fullchain.pem; # managed by Certbot
	ssl_certificate_key /etc/letsencrypt/live/transcoder.domain.com/privkey.pem; # managed by Certbot
	include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
	ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
	
	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;
	
	location /.well-known/acme-challenge {
		auth_basic off;
		allow all;
		alias /var/www/.letsencrypt;
	}
	
	location / {
	
		# Proxy configuration
		proxy_pass http://127.0.0.1:3000;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}
server {
	if ($host = transcoder.domain.com {
		return 301 https://$host$request_uri;
	} # managed by Certbot
	
	listen 80;
	listen [::]:80;
	
	server_name transcoder.domain.com;
	return 404; # managed by Certbot
}
```
for the SSL certificate: https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-18-04

**Comment by Maxou44** [comment]
Nice, thanks for sharing! We will add that to the documentation!

**Comment by raphaelfumfahr** [comment]
Sorry last question:

Does synchronization work in apps? 😅

**Comment by Maxou44** [comment]
Unfortunately it don't work at the moment, I hope it will be supported soon (after Plex 1.15 compatibility).

Unsupported features:
- Sync
- Media optimization
- Auto quality
- Music transcode
