### ISSUE TITLE
Music transcode support

### ISSUE THREAD

**Issue by Maxou44** [UnicornTranscoder/UnicornTranscoder#45]
The music transcode don't work at the moment, it could be nice to fix it. Actually, the load balancer redirects the request but the transcoder don't work (issues with ffmpeg arguments patching ?)

**Comment by drouarb** [comment]
Music transcoding route isn’t implemented, we need to see if the transcoder.js is able to handle that kind of stream

**Comment by Maxou44** [comment]
In the route path, we just need to use a parameter like "/:routeType/" instead of "/video/" and it will catches music transcode requests

**Comment by Maxou44** [comment]
I changed endpoints in c3d9c946986f623539978bae2d86453cc3145f45

**Comment by Maxou44** [comment]
Fixed! #49
