### ISSUE TITLE
Is it possible to transcode 1 stream on multiple nodes within your cluster?

### ISSUE THREAD

**Issue by GijsGoudzwaard** [UnicornTranscoder/UnicornTranscoder#55]
I have a couple of raspberry pi's that I'd like to use to build a cluster. With this cluster I'd like to transcode h265 content on the fly to h264. One pi isn't powerful enough to do this, so maybe a cluster of pi's would be. So my question is is it possible to transcode 1 stream on multiple pi's so that my use case would work?

**Comment by drouarb** [comment]
No it’s not possible, it would be very complicated to implement something like this
