### ISSUE TITLE
The video buffers about 40-60 seconds at the end

### ISSUE THREAD

**Issue by cruex-de** [UnicornTranscoder/UnicornTranscoder#61]
Hey,

I currently have the problem that at the end (40-120 seconds) every episode or movie begins to buffer it. And so e.g. important contents of the episode or film get lost.

My transcoder buffer is 60 seconds.
The transcoding from x264 is set to very fast.
Hardware acceleration is off.

Does anyone have a hint what it is? I already increased the transcoder buffer to 120 but the same result.

**Comment by Maxou44** [comment]
We don't have any issues on our side, please, share us your configurations, type of player and transcoder logs 😉

Do you have the same issue with original Plex  Media Server ?

**Comment by zapoklu** [comment]
I have a similar issue, Approximately 1% of the end of the video does not play. I find this happens mostly when using "Direct play" rather than transcoding. Predominantly using Google Chrome and the web app https://app.plex.tv/desktop , playing MP4 files with H264 AAC.

**Comment by cruex-de** [comment]
> We don't have any issues on our side, please, share us your configurations, type of player and transcoder logs 😉
> 
> Do you have the same issue with original Plex Media Server ?

What do you need about?

The hardware of the transcoder:
CPU: AMD Ryzen 7 1700X
RAM: 64 GB DDR4 RAM
Hard disk: 2 x 500 GB SSD
Connection: 1 GBit/s

The hardware of the Plex Server:
CPU: Intel i7-6700
RAM: 64 GB DDR4 RAM
Hard disk: 2 x 512 GB NVMe SSD
Connection: 1 GBit/s

Use Rclone with google cloud.
rclone settings:

```
Buffer-Size: 16M
Drive-Chunk-Size: 64M
Dir-Cache-Time: 2m
VFS-Read-Chunk-Size: 64M
VFS-Read-Chunk-Size-Limit: 2048M
VFS-Cache-Mode: off
VFS-Cache-Max-Age: 1h
VFS-Cache-Max-Size: off
Log-Level: INFO
User Agent: rclone/1.48
```

and i use "CUSTOM_DOWNLOAD_FORWARD" on LoadBalancer.

**Comment by Xarin** [comment]
I've got the same issue, it seems to effect all of my users (chrome, firefox, Roku, appleTV, etc). I'll try to get some detailed logs soon.

**Comment by Maxou44** [comment]
Can you make a test:

Start an episode on the web version and look what happen to video/audio chunks at the end of the video ?

Can you give us the Plex Transcoder arguments (using the debug mode) ?

It it's happen only with specific codec, can you provide us example files ?

**Comment by Maxou44** [comment]
Maybe it's because we use ffmpeg HTTP callback to detect if the file is available (and plex make read dir every 200ms), maybe last chunks messages aren't sent ?

@drouarb

**Comment by Maxou44** [comment]
Can you try with the 2.3.8 release?

**Comment by cruex-de** [comment]
> Can you try with the 2.3.8 release?

I'll test it and give you a feedback in a few days.

**Comment by cruex-de** [comment]
> Can you try with the 2.3.8 release?

So, the problem at the end wasn't really fixed, now we have another problem that just jumps backwards a few seconds when playing, or just forwards.

**Comment by Maxou44** [comment]
What is your plex version?
We found issues on HLS transcoded streams but nothing on DASH support at the moment, it looks strange 🙄
It's a normal behavior to receive a 404 and retry, original plex have the same behavior.

Note: I think HLS issues as related to 404/retry support, I'll talk with @drouarb to try a fix soon

**Comment by cruex-de** [comment]
> What is your plex version?
> We found issues on HLS transcoded streams but nothing on DASH support at the moment, it looks strange 🙄
> It's a normal behavior to receive a 404 and retry, original plex have the same behavior.
> 
> Note: I think HLS issues as related to 404/retry support, I'll talk with @drouarb to try a fix soon

I always use the default versions in config.js. After patching back to v2.3.8 it works again without 404 fetch errors. (In my test I had not seen any more)

**Comment by Maxou44** [comment]
The transcoder was reinstalled ?
If you have inconsistencies between transcoder plex build and codecs version some issues could happen

**Comment by cruex-de** [comment]
No, I already used the right versions. When I patched back, I installed the right versions, of course.

**Comment by Maxou44** [comment]
Can you try -again- with Plex 1.18.0.1944-f2cae8d6b and the 2.3.10 release? 😉

**Comment by cruex-de** [comment]
> Can you try -again- with Plex 1.18.0.1944-f2cae8d6b and the 2.3.10 release? 😉

No changes... 😕 the forwards and backwards jumps in the middle on movies/episodes are still here. I can give you access to my plex for tests? (nickname please via dm).

(The jumps are completely random, I don't know why.)

**Comment by Maxou44** [comment]
Add me: Maxou44
Can you record logs ?

**Comment by cruex-de** [comment]
> Add me: Maxou44
> Can you record logs ?

Done, yeah i save the screen logs to a file.

**Comment by Maxou44** [comment]
I'll test it :)

**Comment by cruex-de** [comment]
The jumps are just completely random. Sometimes it's quite early, sometimes it takes 10 minutes. With the version (v2.3.8) I didn't have these problems.

**Comment by Maxou44** [comment]
I don't have any issues with Plex Web on you server 🤔
Try to restart your app? 
Any idea to reproduce the bug? Can you make a video where we could see the bug and network requests and provide logs for the same stream?

If it's a jump issue it looks like a manifest parsing issue but I can't reproduce it 🙄

MPD manifest: 
```<?xml version="1.0" encoding="utf-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="urn:mpeg:dash:schema:mpd:2011"
	xmlns:xlink="http://www.w3.org/1999/xlink"
	xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
	profiles="urn:mpeg:dash:profile:isoff-live:2011"
	type="static"
	mediaPresentationDuration="PT1H2M18.4641S"
	maxSegmentDuration="PT16S"
	minBufferTime="PT10S">
	<Period start="PT0S" id="0" duration="PT1H2M18.4641S">
		<AdaptationSet segmentAlignment="true">
			<SegmentTemplate timescale="1" duration="8" initialization="dash/tvcdyrj627rzkx7x6q2p1ut6/$RepresentationID$/initial.mp4" media="dash/tvcdyrj627rzkx7x6q2p1ut6/$RepresentationID$/$Number$.m4s" startNumber="0">
			</SegmentTemplate>
			<Representation id="0" mimeType="video/mp4" codecs="avc1.42c00d" bandwidth="1724000" width="720" height="406">
			</Representation>
		</AdaptationSet>
		<AdaptationSet segmentAlignment="true">
			<SegmentTemplate timescale="1" duration="8" initialization="dash/tvcdyrj627rzkx7x6q2p1ut6/$RepresentationID$/initial.mp4" media="dash/tvcdyrj627rzkx7x6q2p1ut6/$RepresentationID$/$Number$.m4s" startNumber="0">
			</SegmentTemplate>
			<Representation id="1" mimeType="audio/mp4" codecs="mp4a.40.2" bandwidth="162000" audioSamplingRate="48000">
				<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
			</Representation>
		</AdaptationSet>
	</Period>
</MPD>
```

```

  | {"id":"3zpssegcpwk1z5sc27","args":["-codec:0","h264","-codec:2","eac3_eae","-eae_prefix:2","tvcdyrj627rzkx7x6q2p1ut6_","-analyzeduration","20000000","-probesize","20000000","-i","/mnt/unionfs/Eigene Dokus/The Grand Tour (2016)/Season 3/S03E09-Aston, Astronauts and Angelina’s Children/The Grand Tour (2016) - S03E09 - Aston, Astronauts and Angelina’s Children.mkv","-filter_complex","[0:0]scale=w=720:h=406[0];[0]format=pix_fmts=yuv420p\|nv12[1]","-filter_complex","[0:2] aresample=async=1:ocl='stereo':osr=48000[2]","-map","[1]","-codec:0","libx264","-crf:0","21","-maxrate:0","1724k","-bufsize:0","3448k","-r:0","25","-preset:0","veryfast","-x264opts:0","subme=2:me_range=4:rc_lookahead=10:me=dia:no_chroma_me:8x8dct=0:partitions=none","-force_key_frames:0","expr:gte(t,0+n_forced*8)","-map","[2]","-metadata:s:1","language=eng","-codec:1","aac","-b:1","162k","-f","dash","-seg_duration","8","-init_seg_name","init-stream$RepresentationID$.m4s","-media_seg_name","chunk-stream$RepresentationID$-$Number%05d$.m4s","-window_size","5","-delete_removed","false","-skip_to_segment","1","-time_delta","0.0625","-manifest_name","{INTERNAL_TRANSCODER}video/:/transcode/session/tvcdyrj627rzkx7x6q2p1ut6/455a8c55-e8b4-48ad-8364-d2d6763634d1/manifest","-avoid_negative_ts","disabled","-map_metadata","-1","-map_chapters","-1","dash","-start_at_zero","-copyts","-vsync","cfr","-y","-nostats","-loglevel","quiet","-loglevel_plex","error","-progressurl","{INTERNAL_TRANSCODER}video/:/transcode/session/tvcdyrj627rzkx7x6q2p1ut6/455a8c55-e8b4-48ad-8364-d2d6763634d1/progress"],"env":{"EAE_ROOT":"/tmp/pms-f8016b2e-5e21-45e9-94d6-09388b7a3635/EasyAudioEncoder","FFMPEG_EXTERNAL_LIBS":"/var/lib/plexmediaserver/Library/Application\\ Support/Plex\\ Media\\ Server/Codecs/20fed83-2561-linux-x86_64/","HOME":"/home/plex","INVOCATION_ID":"ff54b843d25249c9b9add54ef8caead3","JOURNAL_STREAM":"9:25437","LANG":"en_US.UTF-8","LD_LIBRARY_PATH":"/usr/lib/plexmediaserver/lib","LIBVA_DRIVERS_PATH":"/usr/lib/plexmediaserver/lib/dri","LOGNAME":"plex","PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR":"/var/lib/plexmediaserver/Library/Application Support","PLEX_MEDIA_SERVER_HOME":"/usr/lib/plexmediaserver","PLEX_MEDIA_SERVER_INFO_DEVICE":"PC","PLEX_MEDIA_SERVER_INFO_MODEL":"x86_64","PLEX_MEDIA_SERVER_INFO_PLATFORM_VERSION":"18.04.3 LTS (Bionic Beaver)","PLEX_MEDIA_SERVER_INFO_VENDOR":"Ubuntu","PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS":"6","PLEX_MEDIA_SERVER_TMPDIR":"/tmp","PWD":"/","SHELL":"/bin/bash","USER":"plex","XDG_CACHE_HOME":"/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Cache","XDG_DATA_HOME":"/usr/lib/plexmediaserver/Resources","X_PLEX_TOKEN":"xxxxxxxxxx"},"session":"tvcdyrj627rzkx7x6q2p1ut6","sessionFull":"tvcdyrj627rzkx7x6q2p1ut6/455a8c55-e8b4-48ad-8364-d2d6763634d1","optimize":{}}
```

**Comment by cruex-de** [comment]
Yes, I can make a video if you like.

**Comment by Maxou44** [comment]
I also checked and I don't have any issues at the end of streams 🤔

**Comment by Maxou44** [comment]
Strange bug but not related:

```<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: ENOENT: no such file or directory, stat &#39;/home/transcoder/src/cache/pqox6knmbrjntzco6eg8nnb9/chunk-stream0-00523.m4s&#39;</pre>
</body>
</html>
```

**Comment by cruex-de** [comment]
How can I send you the link of the logs and the video? (at the end of the video it jumps 4-6 seconds)

**Comment by Maxou44** [comment]
Remove plex tokens / url in logs and post it here :)
If we can't see personal info, you can psot video here too :)

**Comment by cruex-de** [comment]
> Remove plex tokens / url in logs and post it here :)
> If we can't see personal info, you can psot video here too :)

i uploaded a .zip here: http://uploaded.net/file/hakkbwbd

**Comment by Maxou44** [comment]
Thanks :)
Can you provide me the output of the manifest.mpd resuest in your devtools ?

**Comment by cruex-de** [comment]
> Thanks :)
> Can you provide me the output of the manifest.mpd request in your devtools ?

Where can I find these?

**Comment by Maxou44** [comment]
In the network page in your browser it's one of the first request when you start a video
Select the last one and you'll have something like that:
```<?xml version="1.0" encoding="utf-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="urn:mpeg:dash:schema:mpd:2011"
	xmlns:xlink="http://www.w3.org/1999/xlink"
	xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
	profiles="urn:mpeg:dash:profile:isoff-live:2011"
	type="static"
	mediaPresentationDuration="PT0H20M28.9041S"
	maxSegmentDuration="PT16S"
	minBufferTime="PT10S">
	<Period start="PT0S" id="0" duration="PT0H20M28.9041S">
		<AdaptationSet segmentAlignment="true">
			<SegmentTemplate timescale="1" duration="8" initialization="dash/nhbzbfokfo8ulc7o7gx3av8d/$RepresentationID$/initial.mp4" media="dash/nhbzbfokfo8ulc7o7gx3av8d/$RepresentationID$/$Number$.m4s" startNumber="0">
			</SegmentTemplate>
			<Representation id="0" mimeType="video/mp4" codecs="avc1.42c00d" bandwidth="1524000" width="720" height="404">
			</Representation>
		</AdaptationSet>
		<AdaptationSet segmentAlignment="true">
			<SegmentTemplate timescale="1" duration="8" initialization="dash/nhbzbfokfo8ulc7o7gx3av8d/$RepresentationID$/initial.mp4" media="dash/nhbzbfokfo8ulc7o7gx3av8d/$RepresentationID$/$Number$.m4s" startNumber="0">
			</SegmentTemplate>
			<Representation id="1" mimeType="audio/mp4" codecs="mp4a.40.2" bandwidth="164000" audioSamplingRate="48000">
				<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
			</Representation>
		</AdaptationSet>
	</Period>
</MPD>
```

**Comment by cruex-de** [comment]
i have only start.mpd here and no manifest.mpd

**Comment by Maxou44** [comment]
My bad it's start.mpd

**Comment by cruex-de** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="urn:mpeg:dash:schema:mpd:2011"
	xmlns:xlink="http://www.w3.org/1999/xlink"
	xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
	profiles="urn:mpeg:dash:profile:isoff-live:2011"
	type="static"
	mediaPresentationDuration="PT0H41M5.43994S"
	maxSegmentDuration="PT2S"
	minBufferTime="PT10S">
	<Period start="PT0S" id="0" duration="PT0H41M5.43994S">
		<AdaptationSet segmentAlignment="true">
			<SegmentTemplate timescale="1" duration="1" initialization="dash/omhnc2eiwgbowwu02m58m541/$RepresentationID$/initial.mp4" media="dash/omhnc2eiwgbowwu02m58m541/$RepresentationID$/$Number$.m4s" startNumber="0">
			</SegmentTemplate>
			<Representation id="0" mimeType="video/mp4" codecs="avc1.42c00d" bandwidth="11205000" width="1920" height="1080">
			</Representation>
		</AdaptationSet>
		<AdaptationSet segmentAlignment="true">
			<SegmentTemplate timescale="1" duration="1" initialization="dash/omhnc2eiwgbowwu02m58m541/$RepresentationID$/initial.mp4" media="dash/omhnc2eiwgbowwu02m58m541/$RepresentationID$/$Number$.m4s" startNumber="0">
			</SegmentTemplate>
			<Representation id="1" mimeType="audio/mp4" codecs="mp4a.40.2" bandwidth="151000" audioSamplingRate="48000">
				<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
			</Representation>
		</AdaptationSet>
	</Period>
</MPD>

```

**Comment by Maxou44** [comment]
Interesting... You don't have the same duration as mine 😮
I'll check logs and I'll keep you informed ;)

**Comment by Maxou44** [comment]
Maybe it could be nice to try with original plex (1.18.x) without Unicorn stuff to see if the bug is related to Plex or our transcoder

**Comment by cruex-de** [comment]
I can try that tomorrow. (With an older version of Plex it worked without any problems, 1.17.0.1841-d42cfa161) Has something special been added to the 18.XX version of Plex?

**Comment by Maxou44** [comment]
I'm runing 1.17.1841 build too but I can't reproduce your bug on my server 🙄

In 1.18.x changelog we can see that:
- (Transcoder) Some packets could randomly be skipped in certain clients, resulting in a “skipping” effect (#10401)

So maybe it's just a random Plex bug 😅

**Comment by cruex-de** [comment]
But this is under Fixes, but I have the problem with the current version (1.18.0.1944) 🤔

**Comment by Maxou44** [comment]
For you the problem is related to Unicorn Transcoder ? 

Transcoder 2.3.8 + plex 1.17 => no issue
Transcoder 2.3.9/10 + plex 1.18 => Issues 

Can you try transcoder 2.3.10 + plex 1.17 ? ( Just change the config.js file to set plex build, codec and eae build)

**Comment by Maxou44** [comment]
The difference between 2.3.8 and 2.3.9/2.3.10 are only 2 lines of code and update build in config.js

These lines can't have an impact on the streaming feature. Maybe it's a bug related to Plex web ? Can you check your version of Plex web ?

**Comment by cruex-de** [comment]
> For you the problem is related to Unicorn Transcoder ?
> 
> Transcoder 2.3.8 + plex 1.17 => no issue
> Transcoder 2.3.9/10 + plex 1.18 => Issues
> 
> Can you try transcoder 2.3.10 + plex 1.17 ? ( Just change the config.js file to set plex build, codec and eae build)

I'm installing this right now. Where can I view the plex web version?

**Comment by Maxou44** [comment]
In the settings of Plex web in Player > General it's 4.x.x version

**Comment by cruex-de** [comment]
> In the settings of Plex web in Player > General it's 4.x.x version

Version 4.10.1 currently

**Comment by cruex-de** [comment]
> The difference between 2.3.8 and 2.3.9/2.3.10 are only 2 lines of code and update build in config.js
> 
> These lines can't have an impact on the streaming feature. Maybe it's a bug related to Plex web ? Can you check your version of Plex web ?

Now it's running perfect again, so I guess it's the new Plex version?

**Comment by Maxou44** [comment]
Can you give us your versions ?

**Comment by cruex-de** [comment]
> Can you give us your versions ?

Which version? for download?

https://downloads.plex.tv/plex-media-server-new/1.17.0.1841-d42cfa161/debian/plexmediaserver_1.17.0.1841-d42cfa161_amd64.deb

**Comment by Maxou44** [comment]
With the last UnicornTranscoder?

**Comment by Maxou44** [comment]
It looks like a Plex related issue, we'll see if the next update fix your bug 😉

**Comment by cruex-de** [comment]
> It looks like a Plex related issue, we'll see if the next update fix your bug 😉

newer than v1.18.0.1944-f2cae8d6b? (I'm just confused.)

**Comment by Maxou44** [comment]
Yes, we'll wait 1.19.x to see if it solve the bug ☺️

**Comment by cruex-de** [comment]
@Maxou44 I just updated the whole thing and the seconds jumps are gone... But now the whole transcoding process stops after 60-120 seconds and the chunks only come with a 404 fetch error message from the transcoder. And then it hangs permanently on buffering.

Plex: 1.18.5.2309-f5213a238
Transcoder: 1.18.5.2309-f5213a238
Codecs: 8bf330d-2818
EAE: eae-69c1de6-42

![Image from my devtool](https://i.gyazo.com/6c363435cadf5d231cabfd85754d714c.png)

[loadbalancer.txt](https://github.com/UnicornTranscoder/UnicornTranscoder/files/4185580/loadbalancer.txt)

[transcoder.txt](https://github.com/UnicornTranscoder/UnicornTranscoder/files/4185582/transcoder.txt)

**Comment by Maxou44** [comment]
I can't reproduce this bug, we run latest version on our side without any issue, I don't understand 😥

**Comment by cruex-de** [comment]
Could it be cloudflare? I activated the proxy there.

**Comment by Maxou44** [comment]
It's not a cloudflare issue

**Comment by cruex-de** [comment]
> It's not a cloudflare issue

Okay... then I have no more ideas what it is...

**Comment by Maxou44** [comment]
What is the content of 404 requests?

**Comment by cruex-de** [comment]
> What is the content of 404 requests?

from a tv show, or what u mean?

**Comment by Maxou44** [comment]
When you have a 404 error in the browser console, can you open the link in a new windows and check the content, normally you'll have "callback xxx"

**Comment by Maxou44** [comment]
Can you check with the 2.4.0 release? We fixed it!

**Comment by cruex-de** [comment]
I'm sorry, I don't use UnicornTranscoder anymore, and can't test it. Since I switched to a single server setup, with an AMD EPYC 7502P.
