### ISSUE TITLE
1 Plex MS, 3 Transcoders - Can't seem to make it work.

### ISSUE THREAD

**Issue by zoltaroth** [UnicornTranscoder/UnicornTranscoder#63]
I've followed the instructions as best I could and I have the following setup:

san-plex => pms + uni-lb + swapped out Plex Transcoder for one built with Unicorn FFMPEG

san-plex-transcode-001 => uni-transcoder at work 3000 pointed at san-plex:3001 

Set the network access info on PMS to be http://san-plex:3000

Try to transcode => nothing happens and the logs are pretty useless. If I try to play a video I just get a blank screen.  san-plex does have a transcoder process running but I cannot see any evidence that san-plex-transcode-001 got the request at all.

What I think should happen:

UniLB comes up and starts routing to PMS
UniTrans comes up and advertises to UniLB that they are alive
(At this point it would be nice if UniLB acknowledged the new transcoder connection but it doesnt maybe it should and this is part of my problem?)

 Any idea where I messed up?

**Comment by Maxou44** [comment]
Can you check if you receive a 302 when a stream start?

**Comment by zoltaroth** [comment]
> Can you check if you receive a 302 when a stream start?

Absolutely.  How?

**Comment by zoltaroth** [comment]
Here are the logs I have:

san-plex:

`[238] (10.10.10.1) nandor:~/dev/UnicornFFMPEG [master]
$ docker logs -f unicorn-lb
Updating permissions...
Updating permissions in /opt/UnicornLoadBalancer...
Updating permissions in /etc/s6.d...
Done updating permissions.

> unicorn-load-balancer@2.0.0 start /opt/UnicornLoadBalancer
> node index.js

2019-08-06T22:18:44.502Z UnicornLoadBalancer Redis not found, fallback on LocalSessionStore
2019-08-06T22:18:44.504Z UnicornLoadBalancer WARNING: On restart all sessions will be lost
2019-08-06T22:18:44.796Z UnicornLoadBalancer Using sqlite as database
2019-08-06T22:18:44.904Z UnicornLoadBalancer Version: 2.0.0
2019-08-06T22:18:44.910Z UnicornLoadBalancer Initializing API routes...
2019-08-06T22:18:44.918Z UnicornLoadBalancer Launched on http://127.0.0.1:3001/
2019-08-06T22:19:38.284Z UnicornLoadBalancer FFMPEG 3tgc77ovqud5hme49txtzgjc [3tgc77ovqud5hme49txtzgjc/17453a5d-77b5-452c-a836-e249dc12d630]
2019-08-06T22:19:38.294Z UnicornLoadBalancer FFMPEG 3tgc77ovqud5hme49txtzgjc [STREAMING]
2019-08-06T22:19:48.317Z UnicornLoadBalancer FFMPEG 40599urjz0dz8af [PING]
2019-08-06T22:19:58.323Z UnicornLoadBalancer FFMPEG 40599urjz0dz8af [PING]
2019-08-06T22:20:08.334Z UnicornLoadBalancer FFMPEG 40599urjz0dz8af [PING]
2019-08-06T22:20:18.344Z UnicornLoadBalancer FFMPEG 40599urjz0dz8af [PING]
2019-08-06T22:20:28.354Z UnicornLoadBalancer FFMPEG 40599urjz0dz8af [PING]
2019-08-06T22:20:38.363Z UnicornLoadBalancer FFMPEG 40599urjz0dz8af [PING]
2019-08-06T22:20:48.365Z UnicornLoadBalancer FFMPEG 40599urjz0dz8af [PING]
2019-08-06T22:20:58.375Z UnicornLoadBalancer FFMPEG 40599urjz0dz8af [PING]
2019-08-06T22:21:08.385Z UnicornLoadBalancer FFMPEG 40599urjz0dz8af [PING]
2019-08-06T22:21:18.396Z UnicornLoadBalancer FFMPEG 40599urjz0dz8af [PING]
[...]`

san-plex-transcoder-001:

`[59] (10.10.10.1) nandor:~/dev/UnicornTranscoder [master]
$ DEBUG=UnicornTranscoder npm start

> UnicornTranscoder@2.2.2 start /home/nandor/dev/UnicornTranscoder
> node ./bin/www

  UnicornTranscoder Starting EAE +0ms`

**Comment by Maxou44** [comment]
can you try `DEBUG=UnicornTranscoder* npm start` ?

**Comment by zoltaroth** [comment]
```
[68] (10.10.10.1) nandor:~/dev/UnicornTranscoder [master]
$ DEBUG=UnicornTranscoder* npm start

> UnicornTranscoder@2.2.2 start /home/nandor/dev/UnicornTranscoder
> node ./bin/www

  UnicornTranscoder Starting EAE +0ms
  UnicornTranscoder2:server Listening on port 3000 +0ms

```

**Comment by zoltaroth** [comment]
> can you try `DEBUG='UnicornTranscoder*' npm start` ?

```
[68] (10.10.10.1) nandor:~/dev/UnicornTranscoder [master]
$ DEBUG=UnicornTranscoder* npm start

> UnicornTranscoder@2.2.2 start /home/nandor/dev/UnicornTranscoder
> node ./bin/www

  UnicornTranscoder Starting EAE +0ms
  UnicornTranscoder2:server Listening on port 3000 +0ms
```

**Comment by Maxou44** [comment]
Can you share us your transcoder configuration ? It looks like the transcoder don't register it to the load balancer

**Comment by zoltaroth** [comment]
> Can you share us your transcoder configuration ? It looks like the transcoder don't register it to the load balancer

```[69] (10.10.10.1) nandor:~/dev/UnicornTranscoder [master]
$ cat config.js
/**
 * Created by drouar_b on 27/04/2017.
 */

const env = require('getenv');

module.exports = {
    port:                  env.int   ('SERVER_PORT',           3000),
    host:                  env.string('SERVER_LISTEN',         '0.0.0.0'),
    transcoder_decay_time: env.int   ('TRANSCODER_DECAY_TIME', 120),
    loadbalancer_address:  env.string('LOADBALANCER_ADDRESS',  'http://10.10.2.16'),
    ping_frequency:        env.int   ('PING_FREQUENCY',        10),
    instance_address:      env.string('INSTANCE_ADDRESS',      'http://10.10.2.21'),

    transcoder: {
        plex_arch:         env.string('PLEX_ARCH',             'amd64'), // Can be: amd64, arm64, armhf, i386
        plex_build:        env.string('PLEX_BUILD',            '1.16.3.1402-22929c8a2'),
        codecs_build:      env.string('CODECS_BUILD',          '21b5515-2321'),
        plex_resources:    env.string('PLEX_RESOURCES',        'plexmediaserver/'),
        temp_folder:       env.string('TEMP_FOLDER',           'cache/'),
        codecs_folder:     env.string('CODECS_FOLDER',         'codecs/'),
        plex_transcoder:   env.string('PLEX_TRANSCODER',       'Plex Transcoder'),
        eae_version:       env.string('EAE_VERSION',           'eae-69c1de6-38'),
        debug:             env.boolish('TRANSCODER_DEBUG',     true),
    },

    performance: {
        maxSessions:        env.int('MAX_SESSIONS',           10),
        maxDownloads:       env.int('MAX_DOWNLOADS',          10),
        maxTranscodes:      env.int('MAX_TRANSCODE',          10),
    },

    //routing: {
    //    'US': 'http://usgateway.myplex.com'
    //},
};
[70] (10.10.10.1) nandor:~/dev/UnicornTranscoder [master]
$
```

**Comment by zoltaroth** [comment]
Are you on slack or discord? this might go faster not on a forum 🗡

**Comment by Maxou44** [comment]
Add me on Discord: Maxou44#5274

LOADBALANCER_ADDRESS is the public url of tour load balancer, if the laod balancer isn't run on 80, you need to set the port "http://168.168.168:3000" for example

Same thing with INSTANCE_ADDRESS, it's the public url where the transcoder can be called

**Comment by zoltaroth** [comment]
> Add me on Discord: Maxou44#5274
> 
> LOADBALANCER_ADDRESS is the public url of your load balancer, if the laod balancer isn't run on 80, you need to set the port "http://168.168.168:3000" for example
> 
> Same thing with INSTANCE_ADDRESS, it's the public url where the transcoder can be called

Updated but still not working:
```
[71] (10.10.10.1) nandor:~/dev/UnicornTranscoder [master]
$ vi config.js
[72] (10.10.10.1) nandor:~/dev/UnicornTranscoder [master]
$ DEBUG=UnicornTranscoder* npm start

> UnicornTranscoder@2.2.2 start /home/nandor/dev/UnicornTranscoder
> node ./bin/www

  UnicornTranscoder Starting EAE +0ms
  UnicornTranscoder2:server Listening on port 3000 +0ms

```

**Comment by zoltaroth** [comment]
```[73] (10.10.10.1) nandor:~/dev/UnicornTranscoder [master]
$ cat config.js
/**
 * Created by drouar_b on 27/04/2017.
 */

const env = require('getenv');

module.exports = {
    port:                  env.int   ('SERVER_PORT',           3000),
    host:                  env.string('SERVER_LISTEN',         '0.0.0.0'),
    transcoder_decay_time: env.int   ('TRANSCODER_DECAY_TIME', 120),
    loadbalancer_address:  env.string('LOADBALANCER_ADDRESS',  'http://10.10.2.16:3001'),
    ping_frequency:        env.int   ('PING_FREQUENCY',        10),
    instance_address:      env.string('INSTANCE_ADDRESS',      'http://10.10.2.21:3000'),
```

**Comment by Maxou44** [comment]
What do you have when  you go to http://loadbalancer:port/api/stats ?

**Comment by zoltaroth** [comment]
> What do you have when you go to http://loadbalancer:port/api/stats ?

```
{
http://10.10.2.21:3000: {
name: "http://10.10.2.21:3000",
sessions: [ ],
settings: {
maxSessions: 10,
maxDownloads: 10,
maxTranscodes: 10
},
url: "http://10.10.2.21:3000",
time: 1565206857,
score: 0
}
}```

**Comment by zoltaroth** [comment]
```[74] (10.10.10.1) nandor:~/dev/UnicornTranscoder [master]
$ DEBUG=UnicornTranscoder* npm start

> UnicornTranscoder@2.2.2 start /home/nandor/dev/UnicornTranscoder
> node ./bin/www

  UnicornTranscoder Starting EAE +0ms
  UnicornTranscoder2:server Listening on port 3000 +0ms
^C
[75] (10.10.10.1) nandor:~/dev/UnicornTranscoder [master]
$ ifconfig
ens192: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.10.2.21  netmask 255.255.0.0  broadcast 10.10.255.255
```

**Comment by Maxou44** [comment]
Ok, so the transcoder is correcly registered, can you launch a stream and give me LB and transcoders logs ?

**Comment by zoltaroth** [comment]
> Ok, so the transcoder is correcly registered, can you launch a stream and give me LB and transcoders logs ?

assuming you mean npm logs:

lb: 

```2019-08-07T19:42:57.470Z UnicornLoadBalancer FFMPEG 43jk4aq6xbjfu9xn1nqfiew1 [43jk4aq6xbjfu9xn1nqfiew1/535e8943-6326-4847-940b-7a87e58ee0d6]
2019-08-07T19:42:57.475Z UnicornLoadBalancer FFMPEG 43jk4aq6xbjfu9xn1nqfiew1 [STREAMING]


2019-08-07T19:43:07.496Z UnicornLoadBalancer FFMPEG 40599xpjz1ntl8j [PING]
2019-08-07T19:43:17.505Z UnicornLoadBalancer FFMPEG 40599xpjz1ntl8j [PING]
```

uni-trans:

```

[76] (10.10.10.1) nandor:~/dev/UnicornTranscoder [master]
$ DEBUG=UnicornTranscoder* npm start

> UnicornTranscoder@2.2.2 start /home/nandor/dev/UnicornTranscoder
> node ./bin/www

  UnicornTranscoder Starting EAE +0ms
  UnicornTranscoder2:server Listening on port 3000 +0ms
```

**Comment by zoltaroth** [comment]
It's almost like the LB isnt seeing the transcode session....

**Comment by Maxou44** [comment]
How do you access to your plex ?
Plex Web ? Can you check the networks requests when you start a video ? 

It's a GET request on https://yourserver/video/:/transcode/universal/start.mpd

The first request on this url need to be a 302 to the transcoder and "http://yourserver" MUST BE your load balancer address, you can't use plex with Plex Relay / Plex DNS Ip / 32400 port

It's why we recommend to setup a nginx and a domain name

**Comment by zoltaroth** [comment]
just as a sanity check:

```[257] (10.10.10.1) nandor:~/dev/UnicornFFMPEG [master]
$ md5sum /usr/lib/plexmediaserver/Plex\ Transcoder
cc26c5439ea0618cefc68d1769ebbd95  /usr/lib/plexmediaserver/Plex Transcoder

[258] (10.10.10.1) nandor:~/dev/UnicornFFMPEG [master]
$ md5sum ~/dev/UnicornFFMPEG/bin/Plex\ Transcoder-linux
cc26c5439ea0618cefc68d1769ebbd95  /home/nandor/dev/UnicornFFMPEG/bin/Plex Transcoder-linux```

**Comment by zoltaroth** [comment]
> How do you access to your plex ?
> Plex Web ? Can you check the networks requests when you start a video ?
> 
> It's a GET request on https://yourserver/video/:/transcode/universal/start.mpd
> 
> The first request on this url need to be a 302 to the transcoder and "http://yourserver" MUST BE your load balancer address, you can't use plex with Plex Relay / Plex DNS Ip / 32400 port
> 
> It's why we recommend to setup a nginx and a domain name

I use http://san-plex:3001/web then I navigate to a movie/tv show and hit play

**Comment by zoltaroth** [comment]
Currently hitting this url:

http://10.10.2.16:3001/web/index.html#!/server/fd06e7af1010b59a9f01c6ceb70f1090aa240c64/details?key=%2Flibrary%2Fmetadata%2F5149

**Comment by Maxou44** [comment]
Yes but Plex will not use this URL it resolve servers itself, can you check in the browser network ?

![image](https://user-images.githubusercontent.com/8138585/62653267-7d7dbc00-b95d-11e9-8f5a-2b3c7e959fcd.png)

**Comment by zoltaroth** [comment]
> Yes but Plex will not use this URL it resolve servers itself, can you check in the browser network ?
> 
> ![image](https://user-images.githubusercontent.com/8138585/62653267-7d7dbc00-b95d-11e9-8f5a-2b3c7e959fcd.png)

```
https://10-10-2-16.1561524e102b4490af8709b7b278fa23.plex.direct:32400/video/:/transcode/universal/start.mpd?hasMDE=1&path=%2Flibrary%2Fmetadata%2F5150&mediaIndex=0&partIndex=0&protocol=dash&fastSeek=1&directPlay=0&directStream=1&subtitleSize=100&audioBoost=100&location=lan&addDebugOverlay=0&autoAdjustQuality=0&directStreamAudio=1&mediaBufferSize=102400&session=f9t7oetc6qqg79ye8ipe6lws&subtitles=burn&Accept-Language=en&X-Plex-Session-Identifier=fqikfh3wn9pb5l7jq18nqi5y&X-Plex-Client-Profile-Extra=append-transcode-target-codec%28type%3DvideoProfile%26context%3Dstreaming%26audioCodec%3Daac%26protocol%3Ddash%29&X-Plex-Product=Plex%20Web&X-Plex-Version=3.104.2&X-Plex-Client-Identifier=e1ohss0876vrkus12e9momkd&X-Plex-Platform=Chrome&X-Plex-Platform-Version=75.0&X-Plex-Sync-Version=2&X-Plex-Model=bundled&X-Plex-Device=Windows&X-Plex-Device-Name=Chrome&X-Plex-Device-Screen-Resolution=1926x815%2C3440x1440&X-Plex-Token=Skf7sMb852ynunARXqd2&X-Plex-Language=en```

**Comment by zoltaroth** [comment]
https://10-10-2-16.1561524e102b4490af8709b7b278fa23.plex.direct:32400/video/:/transcode/universal/start.mpd?hasMDE=1&path=%2Flibrary%2Fmetadata%2F5150&mediaIndex=0&partIndex=0&protocol=dash&fastSeek=1&directPlay=0&directStream=1&subtitleSize=100&audioBoost=100&location=lan&addDebugOverlay=0&autoAdjustQuality=0&directStreamAudio=1&mediaBufferSize=102400&session=f9t7oetc6qqg79ye8ipe6lws&subtitles=burn&Accept-Language=en&X-Plex-Session-Identifier=fqikfh3wn9pb5l7jq18nqi5y&X-Plex-Client-Profile-Extra=append-transcode-target-codec%28type%3DvideoProfile%26context%3Dstreaming%26audioCodec%3Daac%26protocol%3Ddash%29&X-Plex-Product=Plex%20Web&X-Plex-Version=3.104.2&X-Plex-Client-Identifier=e1ohss0876vrkus12e9momkd&X-Plex-Platform=Chrome&X-Plex-Platform-Version=75.0&X-Plex-Sync-Version=2&X-Plex-Model=bundled&X-Plex-Device=Windows&X-Plex-Device-Name=Chrome&X-Plex-Device-Screen-Resolution=1926x815%2C3440x1440&X-Plex-Token=Skf7sMb852ynunARXqd2&X-Plex-Language=en

**Comment by zoltaroth** [comment]
What controls that url?  it seems like it is going directly to PMS still.

**Comment by zoltaroth** [comment]
![image](https://user-images.githubusercontent.com/1300129/62653721-01f71d00-b913-11e9-9667-a0cde99d93d4.png)

**Comment by Maxou44** [comment]
Plex call the Plex software directly and not the load balancer (and it's your issue)

Block the 32400 port from your Plex server, following notes here: 
 https://github.com/UnicornTranscoder/UnicornLoadBalancer#2-notes

**Comment by zoltaroth** [comment]
ok i blocked the port iptables

now my transcoder is getting a requestion and trying to do things.

however:

```--enable-encoder=h264_qsv --enable-encoder=mpeg2_qsv --enable-encoder=hevc_qsv --enable-encoder=h264_vaapi --enable-encoder=hevc_vaapi --enable-encoder=h264_nvenc --enable-encoder=eac3_eae --prefix=/data/jenkins/conan_build/290658151/conan/.conan/data/ffmpeg/1.4-2144ff15c5-0/plex/stable/build/1b0687fcd934d79d8283f84c22c8ab4d016c0fea/transcoder-install --enable-libzvbi --enable-gnutls --enable-libass --enable-librtmp --enable-libopus
  UnicornTranscoder:Transcoder  +1ms
  UnicornTranscoder:Transcoder FFMPEG(stderr):   libavutil      56.  7.101 / 56.  7.101
  UnicornTranscoder:Transcoder   libavcodec     58. 12.102 / 58. 12.102
  UnicornTranscoder:Transcoder   libavformat    58.  9.100 / 58.  9.100
  UnicornTranscoder:Transcoder   libavfilter     7. 12.100 /  7. 12.100
  UnicornTranscoder:Transcoder   libswscale      5.  0.101 /  5.  0.101
  UnicornTranscoder:Transcoder   libswresample   3.  0.101 /  3.  0.101
  UnicornTranscoder:Transcoder  +7ms
  UnicornTranscoder:Transcoder FFMPEG(stderr): Unrecognized option 'crf:0'.
  UnicornTranscoder:Transcoder Error splitting the argument list: Option not found
  UnicornTranscoder:Transcoder  +8ms
  UnicornTranscoder:Transcoder FFMPEG stopped xe9ztttxr1mz40jumvn8n7u1 1 null +2ms
  UnicornTranscoder:Transcoder session xe9ztttxr1mz40jumvn8n7u1 started +8s```

**Comment by zoltaroth** [comment]
ALsoi

```  UnicornTranscoder:Transcoder FFMPEG(stderr): Incompatible FFmpeg versions: '1.4-21b55156f-0' vs. '1.4-2144ff15c5-0'.
  UnicornTranscoder:Transcoder Failed to initialize library.
  UnicornTranscoder:Transcoder  +1ms```

**Comment by Maxou44** [comment]
Okey, so your configuration issue is fixed, now it looks like a build issue.
 
You changed your PLEX_BUILD value but not the CODECS_BUILD and EAE_VERSION, so the Plex build isn't compliant with the transcoder

From your transcoder configuration
`{
   plex_build:        env.string('PLEX_BUILD',            '1.16.3.1402-22929c8a2'),
   codecs_build:      env.string('CODECS_BUILD',          '21b5515-2321'),
   eae_version:       env.string('EAE_VERSION',           'eae-69c1de6-38'),
}`

You can fix it by using the latest Plex build we support (1.16.1) or by finding the CODECS_BUILD and EAE_VERSION for the 1.16.3 build.

After any change in your configuration you need to reinstall the transcoder (to pull libraries)

Maybe @drouarb can quicly find the values?

**Comment by zoltaroth** [comment]
I am rolling back the plex version now... 

So next error:

```  UnicornTranscoder:Transcoder FFMPEG(stderr): [tcp @ 0x251b3c0] Connection to tcp://127.0.0.1:32400 failed: Connection refused
  UnicornTranscoder:Transcoder  +4ms
  UnicornTranscoder:Transcoder FFMPEG(stderr): [tcp @ 0x251c680] Connection to tcp://127.0.0.1:32400 failed: Connection refused
  UnicornTranscoder:Transcoder  +0ms
  UnicornTranscoder:Transcoder FFMPEG(stderr): http://san-plex.ntsj.com:3001library/parts/5370/0/file.stream?download=1: Server returned 401 Unauthorized (authorization failed)
  UnicornTranscoder:Transcoder  +6ms
  UnicornTranscoder:Transcoder FFMPEG(stderr): [tcp @ 0x251bd80] Connection to tcp://127.0.0.1:32400 failed: Connection refused```

**Comment by Maxou44** [comment]
In the load balancer configuration add a "/" after http://san-plex.ntsj.com:3001

Yeah I know we have "/" in the LB config and not in the transcoder 😁

**Comment by zoltaroth** [comment]
Okay I did that but the Transcoder is still trying to connect to localhost:32400 for some unknown reason?

```  UnicornTranscoder:Transcoder FFMPEG(stderr): [tcp @ 0x110e3c0] Connection to tcp://127.0.0.1:32400 failed: Connection refused
  UnicornTranscoder:Transcoder  +5ms
  UnicornTranscoder:Transcoder FFMPEG(stderr): [tcp @ 0x110f680] Connection to tcp://127.0.0.1:32400 failed: Connection refused```

**Comment by Maxou44** [comment]
Can you set in your env `TRANSCODER_DEBUG=true`,  restart your transcoder, and restart a test ?

**Comment by zoltaroth** [comment]
> TRANSCODER_DEBUG=true

Is that an env for the UnicodeTranscoder?  Or the Plex Transcoder binary on the plex host?

**Comment by Maxou44** [comment]
For UnicornTranscoder

**Comment by zoltaroth** [comment]
```UnicornTranscoder:Transcoder Create transcoder 7lvlun81tjgtag6ratphxqub +0ms
  UnicornTranscoder:SessionManager save 7lvlun81tjgtag6ratphxqub +0ms
  UnicornTranscoder:Transcoder [ '-codec:0',
  UnicornTranscoder:Transcoder   'mpeg4',
  UnicornTranscoder:Transcoder   '-codec:#0x01',
  UnicornTranscoder:Transcoder   'ac3',
  UnicornTranscoder:Transcoder   '-analyzeduration',
  UnicornTranscoder:Transcoder   '20000000',
  UnicornTranscoder:Transcoder   '-probesize',
  UnicornTranscoder:Transcoder   '20000000',
  UnicornTranscoder:Transcoder   '-i',
  UnicornTranscoder:Transcoder   'http://10.10.2.16:3001/library/parts/5370/0/file.stream?download=1',
  UnicornTranscoder:Transcoder   '-filter_complex',
  UnicornTranscoder:Transcoder   '[0:0]scale=w=704:h=384[0];[0]format=pix_fmts=yuv420p|nv12[1]',
  UnicornTranscoder:Transcoder   '-filter_complex',
  UnicornTranscoder:Transcoder   '[0:#0x01] aresample=async=1:ocl=\'stereo\':osr=48000[2]',
  UnicornTranscoder:Transcoder   '-map',
  UnicornTranscoder:Transcoder   '[1]',
  UnicornTranscoder:Transcoder   '-codec:0',
  UnicornTranscoder:Transcoder   'libx264',
  UnicornTranscoder:Transcoder   '-crf:0',
  UnicornTranscoder:Transcoder   '16',
  UnicornTranscoder:Transcoder   '-maxrate:0',
  UnicornTranscoder:Transcoder   '1353k',
  UnicornTranscoder:Transcoder   '-bufsize:0',
  UnicornTranscoder:Transcoder   '2706k',
  UnicornTranscoder:Transcoder   '-r:0',
  UnicornTranscoder:Transcoder   '23.975999999999999',
  UnicornTranscoder:Transcoder   '-preset:0',
  UnicornTranscoder:Transcoder   'veryfast',
  UnicornTranscoder:Transcoder   '-x264opts:0',
  UnicornTranscoder:Transcoder   'subme=6:me_range=4:rc_lookahead=10:me=hex:8x8dct=1',
  UnicornTranscoder:Transcoder   '-force_key_frames:0',
  UnicornTranscoder:Transcoder   'expr:gte(t,0+n_forced*8)',
  UnicornTranscoder:Transcoder   '-map',
  UnicornTranscoder:Transcoder   '[2]',
  UnicornTranscoder:Transcoder   '-codec:1',
  UnicornTranscoder:Transcoder   'aac',
  UnicornTranscoder:Transcoder   '-b:1',
  UnicornTranscoder:Transcoder   '256k',
  UnicornTranscoder:Transcoder   '-f',
  UnicornTranscoder:Transcoder   'dash',
  UnicornTranscoder:Transcoder   '-min_seg_duration',
  UnicornTranscoder:Transcoder   '8000000',
  UnicornTranscoder:Transcoder   '-skip_to_segment',
  UnicornTranscoder:Transcoder   '1',
  UnicornTranscoder:Transcoder   '-time_delta',
  UnicornTranscoder:Transcoder   '0.0625',
  UnicornTranscoder:Transcoder   '-manifest_name',
  UnicornTranscoder:Transcoder   'http://127.0.0.1:32400/video/:/transcode/session/7lvlun81tjgtag6ratphxqub/d19bde55-f170-47d8-8dda-ca148c2cf97e/manifest',
  UnicornTranscoder:Transcoder   '-avoid_negative_ts',
  UnicornTranscoder:Transcoder   'disabled',
  UnicornTranscoder:Transcoder   '-map_metadata',
  UnicornTranscoder:Transcoder   '-1',
  UnicornTranscoder:Transcoder   '-map_chapters',
  UnicornTranscoder:Transcoder   '-1',
  UnicornTranscoder:Transcoder   'dash',
  UnicornTranscoder:Transcoder   '-start_at_zero',
  UnicornTranscoder:Transcoder   '-copyts',
  UnicornTranscoder:Transcoder   '-vsync',
  UnicornTranscoder:Transcoder   'cfr',
  UnicornTranscoder:Transcoder   '-y',
  UnicornTranscoder:Transcoder   '-nostats',
  UnicornTranscoder:Transcoder   '-loglevel_plex',
  UnicornTranscoder:Transcoder   'error',
  UnicornTranscoder:Transcoder   '-progressurl',
  UnicornTranscoder:Transcoder   'http://127.0.0.1:32400/video/:/transcode/session/7lvlun81tjgtag6ratphxqub/a8b8c7fe-46f4-4cc2-94ee-2cae5145cfd5/progress' ] +160ms
  UnicornTranscoder:Transcoder Spawn 7lvlun81tjgtag6ratphxqub +8ms
  UnicornTranscoder:Transcoder FFMPEG(stderr): Error loading external lib: /home/nandor/dev/UnicornTranscoder/codecs/21b5515-2321-amd64/libfake_avi_decoder.so: invalid ELF header
  UnicornTranscoder:Transcoder  +11ms
  UnicornTranscoder:Transcoder FFMPEG(stderr): ffmpeg version 1.4-21b55156f-0 Copyright (c) 2000-2018 the FFmpeg developers
  UnicornTranscoder:Transcoder   built with clang version 5.0.1 (tags/RELEASE_501/final)
  UnicornTranscoder:Transcoder  +91ms
  UnicornTranscoder:Transcoder FFMPEG(stderr):   configu```

**Comment by zoltaroth** [comment]
even if the 127. IP was correct it wouldnt work because we dropped all traffic to 32400 :)

**Comment by Maxou44** [comment]
Can you check in your LoadBalancer configuration :

'PLEX_HOST' => '127.0.0.1'
'PLEX_PORT' => 32400

**Comment by zoltaroth** [comment]
```docker create --name unicorn-lb \
              -p 3001:3001 \
              -v /var/lib/plexmediaserver:/var/lib/plexmediaserver \
              -v /usr/lib/plexmediaserver:/usr/lib/plexmediaserver \
              -e DEBUG="UnicornLoadBalancer*" \
              -e PLEX_HOST='10.10.2.16' \
              -e PLEX_PORT=32400 \
              -e SERVER_PUBLIC="http://10.10.2.16:3001/" \
              -e SERVER_HOST='10.10.2.16' \
              -e SERVER_PORT=3001 \
                nandordocker/plex-unicorn-lb:latest
```
```
[287] (10.10.10.1) nandor:~/dev/plexunicorndocker/unicorn-transcoder/load-balancer [master]
$ docker exec -it unicorn-lb /bin/sh
/ # env
SERVER_PUBLIC=http://10.10.2.16:3001/
HOSTNAME=11b7cb748d4b
DEBUG=UnicornLoadBalancer*
SHLVL=1
HOME=/root
PLEX_HOST=10.10.2.16
TERM=xterm
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
GID=991
PLEX_PORT=32400
UID=991
SERVER_HOST=10.10.2.16
PWD=/
SERVER_PORT=3001
/ #
```

**Comment by Maxou44** [comment]
Your LoadBalancer isn't bundle in your Plex docker ?

**Comment by zoltaroth** [comment]
Plex isnt ina  docker its just running on the server.  only the LB is inside a docker

**Comment by zoltaroth** [comment]
I can run it outside of docker if that would help but I dont think it should matter...

**Comment by Maxou44** [comment]
We use PLEX_HOST and PLEX_PORT to determine how we can patch arguments, I tried to publish a fix on the load balancer, can you try it ?

https://github.com/UnicornTranscoder/UnicornLoadBalancer/commit/ebc4a930b428c0bccb2ef70871a02e5e59507455

**Comment by zoltaroth** [comment]
That fixed the errors but I am still not getting video :(

```der=hevc_vaapi --enable-encoder=h264_nvenc --enable-encoder=eac3_eae --prefix=/data/jenkins/conan_build/290396004/conan/.conan/data/ffmpeg/1.4-21b55156f-0/plex/stable/build/1b0687fcd934d79d8283f84c22c8ab4d016c0fea/transcoder-install --enable-libzvbi --enable-gnutls --enable-libass --enable-librtmp --enable-libopus
  UnicornTranscoder:Transcoder   libavutil      56.  7.101 / 56.  7.101
  UnicornTranscoder:Transcoder   libavcodec     58. 12.102 / 58. 12.102
  UnicornTranscoder:Transcoder   libavformat    58.  9.100 / 58.  9.100
  UnicornTranscoder:Transcoder   libavfilter     7. 12.100 /  7. 12.100
  UnicornTranscoder:Transcoder   libswscale      5.  0.101 /  5.  0.101
  UnicornTranscoder:Transcoder   libswresample   3.  0.101 /  3.  0.101
  UnicornTranscoder:Transcoder  +0ms
  UnicornTranscoder:Transcoder session m98ujp6ndubmdtm025nvws6y started +10s
```

**Comment by Maxou44** [comment]
What is the issue exactly ?

Can you acess to http://10.10.2.16:3001/library/parts/5370/0/file.stream?download=1 ?

**Comment by zoltaroth** [comment]
I just get a orange spinner and no video starts.

**Comment by zoltaroth** [comment]
> What is the issue exactly ?
> 
> Can you acess to http://10.10.2.16:3001/library/parts/5370/0/file.stream?download=1 ?

```2019-08-07T21:04:14.553Z UnicornLoadBalancer DOWNLOAD 5370 [LB]
2019-08-07T21:04:14.558Z UnicornLoadBalancer DOWNLOAD FAILED 5370 [LB]
2019-08-07T21:04:18.807Z UnicornLoadBalancer DOWNLOAD 5370 [LB]
2019-08-07T21:04:18.810Z UnicornLoadBalancer DOWNLOAD FAILED 5370 [LB]
2019-08-07T21:05:04.674Z UnicornLoadBalancer DOWNLOAD 5370 [LB]
```

**Comment by zoltaroth** [comment]
![image](https://user-images.githubusercontent.com/1300129/62657978-85693c00-b91c-11e9-854e-6073fb2c7b4d.png)

**Comment by Maxou44** [comment]
The loadbalancer need to have aces to your library files

**Comment by zoltaroth** [comment]
oh like the phsical media?

**Comment by zoltaroth** [comment]
Yep!  that fixed it.  I mounted the nfs volume to the docker container and boom!  Wow awesome!
  Thanks!

**Comment by Maxou44** [comment]
Awesome! have a great stream! I'll close the issue, can you share your docker commands, and the docker repository where you found it?

**Comment by zoltaroth** [comment]
Yes I am going to clean it all up tongiht and create a script so I can deploy this to 3 more transcoder servers and then I will update this thread.

**Comment by zoltaroth** [comment]
As promised I have created some *very basic* documentation and two docker images that can be used to deploy unicorn-loadbalancer and unicorn-transcoder quickly and easily.  I was able to deploy this image to 3 hosts in just under 5 minutes each.

I have not created a docker image for unicorn-ffmpeg because that would really be a container for plexmediaserver as all that project does is create a new binary to replace the existing ones in PMS.

unicorn-loadbalancer: https://github.com/zoltaroth/unicorn-lb-docker

unicorn-transcoder: https://github.com/zoltaroth/unicorn-transcoder-docker

Hope someone finds this useful!

Transcoding 4 videos across 3 hosts in my setup:

![image](https://user-images.githubusercontent.com/1300129/62676684-7906d280-b960-11e9-9f71-86de1423495b.png)

**Comment by zoltaroth** [comment]
@Maxou44  let me know if you want to make any changes to those containers or if you want to pull them into a project owned by you all.

**Comment by Maxou44** [comment]
We will rework it a bit I think, I'll keep you informed 😏

**Comment by zoltaroth** [comment]
Yah I left my network info in there it could be replaced with some more generic stuff and all the env vars could be exposed but once it is dailed in it would be a really easy way to deploy this project.

> We will rework it a bit I think, I'll keep you informed 😏
