### ISSUE TITLE
Question: Horizontal scaling of transcoders in Kubernetes, Looking for some input

### ISSUE THREAD

**Issue by zapoklu** [UnicornTranscoder/UnicornTranscoder#67]
Hi there,
I’ve been working with UnicornTranscoder as a direct install and most recently using the magn2o/unicorn-transcoder docker container in Kubernetes. I host my plex + loadbalancer on a remote VM and plex transcoders run on the home network. I’ve setup a singular ingress point into my home which points at my kubernetes service running the transcoders. This is achieved by using NGINX-Ingress in conjunction with a nodeport service and metalLB.

This configuration works quite well when using a small subset of pods, but begins to experience issues when horizontally scaling the number of pods.

Based on the logs I’ve reviewed and the data I have available to me I suspect this is due to the round robin nature of the load balancing performed between the kubernetes pods which causes duplicate work to be performed, thus one job can easily saturate all available CPU. I’ve set resource limits on the individual containers, but obviously if the job rotates to a container other than the one it hit originally, the data does not exist there and files get re-encoded unnecessarily.

To address this, I can think of 2 possible solutions:
1>	Create a loadbalancer with session affinity (Aka sticky sessions) to ensure that each client binds to a specific pod in the cluster. This is a valid strategy however is not as resilient to individual node/pod failure. In addition, from what I’ve read this essentially limits options to cloud based load balancers or a rather expensive version of NGINX Plus ingress controller to get data into the kubernetes service.

2>	Share cache related data between the pods using a shared file system or database (This is considered the more kubernetes-like approach from the reading I’ve done) 

To test the second option, I’ve attempted to mount the subfolder “cache” in the UnicornTranscoder folder (Mounted under /opt/UnicornTranscoder/cache inside the container) as an NFS persistent volume running on another machine on my network. 

This does work to some degree but still seems to have a few issues so I’m interested to understand if there’s a better way to do this. 

If this is the right approach, is sharing the cache folder sufficient? If not, what else would need to be shared? Would a file system even work properly or is this going to require a stateful set and/or a database to hold the information to ensure integrity etc.?

I’m by no means an expert on Kubernetes or Load Balancing and I’ve managed to get a lot of this working by sheer brute force. I’m more than happy to share any info that will assist.

**Comment by Maxou44** [comment]
The load balancer already have "sticky sessions", when a session starts it will choose a server and all the requests will be made with it.

I think your issue is related to your ingress configuration. To have best performance, each transcoder need to have it's own ip/url. If I'm right, in your case you only have a url for all the transcoder, you'll bandwidth and performance issues.

**Comment by Maxou44** [comment]
Also you can't easily scale on kubernetes, because ffmpeg / Plex Transcoder limit it own speed. Because of that we can't scale on cpu/ram values

The best way is to usr the "score" calculated by the UnicornLoadBalancer

**Comment by Maxou44** [comment]
The architecture of our project is to avoid to share data between transcoder. There is no reason to do it (you'll lose performance and having issues)
