### ISSUE TITLE
External Connections Varying results

### ISSUE THREAD

**Issue by psyciknz** [UnicornTranscoder/UnicornTranscoder#69]
Related to https://github.com/UnicornTranscoder/UnicornTranscoder/issues/39

I have the following:
Internal LB address: LB:3001
Internal Plex address: plex:32400

Slave: Slave:3991 points to LB:3001 (does the slave use the internal load balancer name, or external?

External port (old plex port before using unicorn 2530 > plex:32400)
External SSL: plex.domain.com > LB:3001
Plex custom url set to https://plex.domain.com:443

Local Access.
So, if I navigate to LB:3001 I get the plex page.  It says not secure (fine, it's local), and when I hit play I can see the transcoder kick into gear and start playing.

Access via app.plex..tv
Site is accessible, says it's secure.
But any video I see logging hit the balancer, but nothing goes to the transcoder.  Gets a S1002 (network) error.  I'm not sure what to look for in the logs to diagnose.  Nothing jumps out and says error to me.

Access via https://plex.domain.com
Site is accessible (after kicking me to app.plex.tv) then sends me back to my domain.
Can't play (as iphone doesn't like the video, but I can see in the dashboard that  it think something is transcoding, but looking at the transcoder logs on the slave, they never move.

Access via IOS (I did see in the linked issue, something about removing Plex Relay which I did)
BUt I've probably busted something as it's stopped again now (lists as offline).

Any ideas, of where to start looking at this?

**Comment by Maxou44** [comment]
Can you share us your plex version and your configurations?

**Comment by psyciknz** [comment]
Actually I'll close.  

I had the added complication of running through https://github.com/magn2o/unicorn-docker

While I thought your solution worked quite well  (was great to see the slaves kicking into gear when dealing with local lan access), having to change the network configuration to get it working and add dependencies pushed me to look at PRT instead which seemed a little more lightweight.
