### ISSUE TITLE
A support section or step by step guide ?

### ISSUE THREAD

**Issue by ToxicMushroom** [UnicornTranscoder/UnicornTranscoder#72]
The guides atm are cut short and miss some essential stuff and with some documentation thrown in 
I tried my best but even when connecting directly to port 3001 I get no video back, no console output on loadbalancer or on the transcoder.

I'm uncertain about some things like if the transcoder can be local or needs a domain and is accessed remote.

**Comment by Maxou44** [comment]
We need logs and configuration, information about logs are available here : 
https://github.com/UnicornTranscoder/UnicornTranscoder/blob/master/README.md#logging--debug

Also keep in mind it's a tech project, when you use this kind of software you need some prerequisite, it's really complex, it's VB not for a anyone 🙃

**Comment by Maxou44** [comment]
Any news on your side @ToxicMushroom ?

**Comment by ToxicMushroom** [comment]
Oh sorry I forgot to reply. I didn't have much time this week so I reverted my stuff after it didn't work.
I'm going to try again this weekend and provide you with logs and configs. :)

**Comment by ToxicMushroom** [comment]
Sorry for the late response. Instead of doing it the hard way I'm just hosting my plex server on the laptop that can transcode now. You can close this issue if you want. sorry for wasting your time
