### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by cruex-de** [UnicornTranscoder/UnicornTranscoder#76]
Hey, I have a problem with the installation of the nodejs pkg when I do "npm install" the following appears: 

```
Running "run:geoip" (run) task
Checking  https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.md5
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND geolite.maxmind.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'geolite.maxmind.com'
}
Warning: non-zero exit code 1 Use --force to continue.

Aborted due to warnings.

npm ERR! Linux 4.15.0-65-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! UnicornTranscoder@2.2.2 install: `grunt`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the UnicornTranscoder@2.2.2 install script 'grunt'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the UnicornTranscoder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs UnicornTranscoder
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls UnicornTranscoder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/transcoder/src/npm-debug.log
```

npm -v
6.13.4
node --version
v12.14.0

it looks like a dns problem with geolite.maxmind.com or am I wrong?

i found this:
https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/

> On December 30, 2019, downloads will no longer be served from our public GeoLite2 page, from 
> geolite.maxmind.com/download/geoip/database/*, or from any other public URL.
> 
> To continue using GeoLite2 databases:
> 
> 1. Review our new GeoLite2 EULA.
> 2. Sign up for a MaxMind account.

**Comment by Maxou44** [comment]
Yes, it's an https issue on https://geolite.maxmind.com/

If you don't use geo data, you can ignore this install task

@drouarb

**Comment by ingvaldlorentzen** [comment]
How do you ignore the install task? 

Also, seems like it’s more than an https issue, seems like it’s a licensing issue with GeoLite. 
The Tautulli project had a similar issue and fixed it in the following release: https://github.com/Tautulli/Tautulli/releases/tag/v2.1.40

**Comment by cruex-de** [comment]
> How do you ignore the install task?
> 
> Also, seems like it’s more than an https issue, seems like it’s a licensing issue with GeoLite.
> The Tautulli project had a similar issue and fixed it in the following release: https://github.com/Tautulli/Tautulli/releases/tag/v2.1.40

Yes it is a licensing problem with GeoLite, as I mentioned above. I had simply uncommented the things in the "Grundfile.js".

**Comment by Maxou44** [comment]
Geoip disabled here: https://github.com/UnicornTranscoder/UnicornTranscoder/commit/3ea7e88353bbcf0778c93f61eceb919a42ebd0b6
