### ISSUE TITLE
Question..Help!

### ISSUE THREAD

**Issue by alastair147** [UnicornTranscoder/UnicornTranscoder#79]
Hey!

So I followed all the steps in the notes etc..
I even ended up following #63 

I have a windows plex machine running, with the LB running on it as well. I blocked all access to plex directly on that machine other than LocalHost.. I have the transcoder running on a ubuntu machine. 

Looking like this: 

`root@PLEXTRANS1:/home/banx/Downloads/UnicornTranscoder-master# DEBUG='UnicornTranscoder*' npm start

> UnicornTranscoder@2.2.2 start /home/banx/Downloads/UnicornTranscoder-master
> node ./bin/www

  UnicornTranscoder Starting EAE +0ms
  UnicornTranscoder2:server Listening on port 3000 +0ms

`

But even well trying to play a video, it just goes round and around and around for a while then plex says: Error code: s1001 (Network)

The Transcoder is there and registered to the LB, but I just can't seem to make it play a video.
Any help would be amazing. Thanks!

**Comment by alastair147** [comment]
I can't see port 3000 listening? If it is meant to..

**Comment by Maxou44** [comment]
Can you provide logs, configuration and network browser tool when you try to stream a file ?

**Comment by alastair147** [comment]
![image](https://user-images.githubusercontent.com/5151117/74382881-074d9b00-4e53-11ea-9716-9ca26352cc40.png)

Which logs are you after?
`/**
 * Created by drouar_b on 27/04/2017.
 */

const env = require('getenv');

module.exports = {
    port:                  env.int   ('SERVER_PORT',           3000),
    host:                  env.string('SERVER_LISTEN',         '127.0.0.1'),
    transcoder_decay_time: env.int   ('TRANSCODER_DECAY_TIME', 120),
    loadbalancer_address:  env.string('LOADBALANCER_ADDRESS',  'http://192.168.188.88:3001'),
    ping_frequency:        env.int   ('PING_FREQUENCY',        10),
    instance_address:      env.string('INSTANCE_ADDRESS',      'http://192.168.188.17:3000'),

    maxmind_key:           env.string('MAXMIND_KEY',           ''),

    transcoder: {
        plex_arch:         env.string('PLEX_ARCH',             'amd64'), // Can be: amd64, arm64, armhf, i386
        plex_build:        env.string('PLEX_BUILD',            '1.18.6.2368-97add474d'),
        codecs_build:      env.string('CODECS_BUILD',          '8bf330d-2818'),
        eae_version:       env.string('EAE_VERSION',           'eae-69c1de6-42'), // 41 or 42?
        plex_resources:    env.string('PLEX_RESOURCES',        'plexmediaserver/'),
        temp_folder:       env.string('TEMP_FOLDER',           'cache/'),
        codecs_folder:     env.string('CODECS_FOLDER',         'codecs/'),
        plex_transcoder:   env.string('PLEX_TRANSCODER',       'Plex Transcoder'),
        debug:             env.boolish('TRANSCODER_DEBUG',     true),
    },

    performance: {
        maxSessions:        env.int('MAX_SESSIONS',           10),
        maxDownloads:       env.int('MAX_DOWNLOADS',          10),
        maxTranscodes:      env.int('MAX_TRANSCODE',          10),
    },

    //routing: {
    //    'US': 'http://usgateway.myplex.com'
    //},
}; `

I haven;t found a way to get the latest codec builds etc, only the latest plex build on windows. So if you know how to get that, do feel free to let me know

**Comment by drouarb** [comment]
In your browser devtools screenshot we can't see any request to the transcoder. Once you start your stream your browser should call a start.mpd, this start.mpd should answer a HTTP 302 to a start.mpd on your transcoder domain, then the stream should start.

For the logs, if you don't get any using `DEBUG='UnicornTranscoder*' npm start`, it means that there is no request reching your transcoder. It probably means that you misconfigured something. Your UnicornTranscoder config looks fine, it is probably that your requests aren't going through UnicornLoadBalancer.

For the codec build it's a bit complicated to find since it's hardcoded in Plex Media Server binary. If you update the PLEX_BUILD without updating the CODECS_BUILD, it will probably not work. All the procedure to update CODECS_BUILD and PLEX_BUILD is explained in the README.

PS: The UnicornTranscoder haven't been tested on a windows PMS, it is possible that Plex is inconsistent between Windows and Linux

**Comment by alastair147** [comment]
So I got all the right info now. 
We switched to Linux for everything!

But when we try stream, the start.mpd gets a 500 error Internal Server Error. 
Any suggestions on what might cause that?

**Comment by alastair147** [comment]
We finally got it talking to each other and pushing logs out.
But we are now getting session wasn't launched in time? Request failed.

Here is what we see in chrome
![image](https://user-images.githubusercontent.com/5151117/74474395-4a1e7a00-4f0a-11ea-8617-f4aea33695f5.png)

**Comment by drouarb** [comment]
So now you should look at transcoder logs

**Comment by davidjameshowell** [comment]
I would also investigate to see how Plex Transcoder on the PMS Master side is too - make sure requests are being sent to your redis server properly.
