### ISSUE TITLE
Session Time out after during transcoding

### ISSUE THREAD

**Issue by Phet0902** [UnicornTranscoder/UnicornTranscoder#85]
Nower days I receive the following message playing 'direct play'

UnicornTranscoder:Transcoder Failed to start ku3wwpr7k1byydsz08ut9n1n: StatusCodeError: 400 - "{\"error\":{\"code\":\"SESSION_TIMEOUT\",\"message\":\"The session wasn't launched in time, request fails\"}}" +21s

To start a move in transcoded version never reaches the status of playing (plex keeps buffering)

  UnicornTranscoder:Transcoder FFMPEG(stderr): [dash @ 0x2ba3a40] Opening 'http://127.0.0.1:3000/video/:/transcode/session/w7s5dcrsd8szwaeo744amoqe/f6f60841-b59a-4dcf-9540-f9e29c35747f/manifest?X-Plex-Http-Pipeline=infinite' for writing
  UnicornTranscoder:Transcoder  +327ms
  UnicornTranscoder:Transcoder FFMPEG(stderr): [dash @ 0x2ba3a40] Opening 'chunk-stream0-00003.m4s.tmp' for writing
  UnicornTranscoder:Transcoder  +1ms
  UnicornTranscoder:Transcoder FFMPEG(stderr): [dash @ 0x2ba3a40] Opening 'chunk-stream1-00003.m4s.tmp' for writing
  UnicornTranscoder:Transcoder  +18ms
  UnicornTranscoder:Dash Serving chunk-stream0-00001.m4s for session w7s5dcrsd8szwaeo744amoqe +22s
  UnicornTranscoder:Dash Serving chunk-stream1-00001.m4s for session w7s5dcrsd8szwaeo744amoqe +89ms
  UnicornTranscoder:Dash Serving init-stream1.m4s for session w7s5dcrsd8szwaeo744amoqe +46ms
  UnicornTranscoder:Dash Serving init-stream0.m4s for session w7s5dcrsd8szwaeo744amoqe +34ms
  UnicornTranscoder:SessionManager ku3wwpr7k1byydsz08ut9n1n not found, restarting (DASH) +18s

Would you know what is the cause for this behavior?

**Comment by Maxou44** [comment]
It's not a direct play issue, you are transcoding the file, can you try:
- Check you correctly replaced the Plex Transcoder binary
- Check the url of your load balancer url in your transcoder configuration

**Comment by Phet0902** [comment]
The Plex transcoder binary has been replaced with the version of 'UnicornFFMPEG'

the URL https://subdomain.mydomain,net point to my Loadbalancer on another server

**Comment by Maxou44** [comment]
Can you share the configuration of UnicornFFmpeg and UnicornLoadBlaancer?

**Comment by Phet0902** [comment]
Can I PM the config to you? Well I use environment variables ;)

**Comment by Maxou44** [comment]
Of course: m.baconnais@outlook.com

**Comment by Phet0902** [comment]
Thanks, on its way

**Comment by Maxou44** [comment]
Got it!

- Can you publish the result of a `https://loadbalancer.com/api/stats` ?
- Are you sure the transcoder have access to the load balancer on public network?
- Are you sure your database path is correct?
- Did you blocket the 32400 port ?
- Did you removed Plex Relay binary ?

**Comment by Phet0902** [comment]
point #1: shows {} only

point #: express:router dispatching GET /api/stats +17s
  express:router query  : /api/stats +1ms
  express:router expressInit  : /api/stats +0ms
  express:router corsMiddleware  : /api/stats +0ms
  express:router jsonParser  : /api/stats +0ms
  body-parser:json skip empty body +17s
  express:router urlencodedParser  : /api/stats +0ms
  body-parser:urlencoded skip empty body +1ms
  express:router <anonymous>  : /api/stats +1ms
  express:router dispatching POST /api/update +54s
  express:router query  : /api/update +0ms
  express:router expressInit  : /api/update +0ms
  express:router corsMiddleware  : /api/update +0ms
  express:router jsonParser  : /api/update +0ms
  body-parser:json content-type "application/json" +54s
  body-parser:json content-encoding "identity" +2ms
  body-parser:json read body +0ms
  body-parser:json parse body +37ms
  body-parser:json parse json +0ms
  express:router urlencodedParser  : /api/update +39ms
  body-parser:urlencoded body already parsed +0ms
  express:router <anonymous>  : /api/update +1ms
point #3: Yes is blocked on Loadbalancer Server

point #4: Yes I did

**Comment by Maxou44** [comment]
If `/api/stats` is empty, your transcoder isn't registered to your loadbalancer, the issue start here, your transcoder can't contact your loadbalancer 🤨

**Comment by Phet0902** [comment]
Send you PM

**Comment by Maxou44** [comment]
So your `api/stats` works: the transcoder is registered to the loadbalancer.
Do you always have the issue? Can you reproduce it step by step ?

**Comment by Phet0902** [comment]
Normal if I chose 'Direct play' I have no issues, it route the call from LB in Germany to my transcoder in Singapore. But once I start transcoding (iPhone/iPad) it will not start the movie. I Plex it keeps saying "Buffering"

**Comment by Maxou44** [comment]
I saw in your configuration CUSTOM_DOWNLOAD_FORWARD=true
Your medias files are mounted on your transcoder serveur ? On the same location than the load balancer ?

**Comment by Phet0902** [comment]
Yes they are (GTeamDrive)

**Comment by Maxou44** [comment]
I don't know, maybe @drouarb have an idea?

**Comment by drouarb** [comment]
If you have a session timeout, it means that the LoadBalancer didn't recieved Plex Transcoder arguments. This can come:
* You didn't replaced `Plex Transcoder` binary in the plex folder (`/usr/lib/plexmediaserver/`) with UnicornFFMPEG.
* UnicornFFMPEG isn't properly configured to your LoadBalancer. (Remember, you need to rebuild UnicornFFMPEG if you change the configuration)
* UnicornTranscoder failed to request Plex to start the session

This error means that you got redirected from the Transcoder but it can't fetch transcoding arguments
With the environement `DEBUG=*` in UnicornLoadBalancer logs you should first see a request to `/api/plex/video/:/transcode/universal/start.mpd`
then a requests to `/api/ffmpeg/<sessionId>`

**Comment by Phet0902** [comment]
Hi thanks for the feedback:

Point #1: Plex Transcoder has been changed with UnicornFFMPEG
Point #2: UnicornFFMPEG is on the same Server as the LoadBalancer. Therefore the URL_LB='127.0.0.1' [Unless this must be the Public IP]

I'd built a TransCoder Server in AMS, with the same configuration. This is working without any problem, Direct Play and Transcoded, too.

Could it have something to du with the higher Latency to SIN (+230ms). I know from my own experience that some apps can't handle high latencies.

**Comment by Maxou44** [comment]
There is a timeout of 20 seconds when we try to start a session, maybe it's the issue ?

**Comment by Phet0902** [comment]
Well from my testing I can say that it is latency problem. The LB stays in a DC in GER. One Server with TransCoder in the same DC. Result no Problem with Direct Play and transcoded Movies. Other Server with TransCoder in DC AMS, alo no problems. However Serer with TransCoder in SIN, plays sometime Direct Pay but never transcoded Movies

**Comment by Maxou44** [comment]
Thanks for your feedback, happy to hear it's not a software issue 👌
Feel free to reopen the issue if needed 😉

**Comment by Phet0902** [comment]
Is there a chance to change the timeout time of 20 seconds?

**Comment by Maxou44** [comment]
Because it's not recommended for regular users, we don't want to increase the timeout value, I invite you to edit the code here:
https://github.com/UnicornTranscoder/UnicornLoadBalancer/blob/master/src/store/local.js#L32

**Comment by Phet0902** [comment]
Great, thank you, I will give you my feedback

**Comment by Maxou44** [comment]
Awesome! 👌
