### ISSUE TITLE
Session Timeout - The session wasn't launched in time, request fails

### ISSUE THREAD

**Issue by kriefsacha** [UnicornTranscoder/UnicornTranscoder#93]
Hi.

I'm quite new in this i will try to give you all the infos i have, if you need more please tell me.

First of all i have to say that i looked at the issue [#85 ](https://github.com/UnicornTranscoder/UnicornTranscoder/issues/85) and did what you asked.

I have two Linux VM's on separates computers on the same network to do a test before we put it in production.

Both have the last version of Linux's Plex Media Server.

First one (master) with load balancer and plex server , second one (worker) with transcoder , ffmpeg and plex server.

I succeeded to connect the load balancer to my worker VM (i see on the `api/stats` with maxSessions , downloads and transcodes at 10).

The thing is when the worker is about to transcode i have the error : 

> Failed to start lbqvrn9gfxd7udfuju10tpw2: StatusCodeError: 400 - "{\"error\":{\"code\":\"SESSION_TIMEOUT\",\"message\":\"The session wasn't launched in time, request fails\"}}"

I did replaced the Plex Transcoder on the 

> UnicornTranscoder/plexmediaserver/1.19.3.2764-ef515a800/usr/lib/plexmediaserver/

 with the one of FFMPEG but i have few questions about that.

1- You say Plex Transcoder needs Plex Server , but i saw and understood after , that it did took the server and puted in the repository. I didn't understood that before and installed Plex Media Server on the worker as weel. Do you think it could be because of it ?

2- I suppose but just to be sure , the Plex Transcoder instance we need to replace from FFMPEG is the one in the plexmediaserver of FFMPEG if we just need this one and no need to install Plex Media Server on workers.

3- My workers (with transcoder and ffmpeg only) and my master (with loadbalancer and Plex Media Server) will be on separate servers, but transcoder have also Plex Media Server in it , it needs to be connected to the Plex Media Server i have on my master somehow ? Or it's just to do the transcoding it's needed ?

4- I see on your pull requests that you begun to support Plex version 1.19.2.27.37 ... since a few days. I have version 1.19.3.2764-ef515a800 (last version). Can be because of it (before i begin to change everything) ?

As i saied if you need infos feel free. Thank you !

**Comment by kriefsacha** [comment]
I already have answers to questions.

I changed the version of plex to the last one you support (1.19.2.2737-b69929dab) , i deleted it from the worker , i compiled FFMPEG again and moved the transcoder to UnicornTranscoder plexmediaplayer .. Same thing.

In the homepage of the transcoder i see it's correctly launched with the correct build version.

So i don't see what i'm missing.

**Comment by Maxou44** [comment]
You need to replace the **original** Plex Trancoder (on your plex server), it's a tricky hack, this fake binary will alert the load balancer when Plex try to start a transcode

**Comment by kriefsacha** [comment]
@Maxou44 it worked !!

I actually did some tests , worked on computers but when i tried on Android it didn't worked.. Without any error message.

I will maybe try on Xbox , Playstation and SmartTV if i can.

**Comment by Maxou44** [comment]
There is a PR about the Android bug, we will fix it soon in a new update

**Comment by Maxou44** [comment]
The bug was fixed in 2.6.x release, feel free to update and have fun 😉
